.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH prefix 1  "prefix 1.1.1" 
.SH NAME
prefix \- A customizable pretty printer for FIX messages
.SH SYNOPSIS
\fBprefix\fR [\fB\-c\fR|\fB\-\-color\fR] [\fB\-d\fR|\fB\-\-delimiter\fR] [\fB\-s\fR|\fB\-\-strip\fR] [\fB\-S\fR|\fB\-\-summary\fR] [\fB\-t\fR|\fB\-\-tag\fR] [\fB\-v\fR|\fB\-\-value\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fImessage\fR] 
.SH DESCRIPTION
A customizable pretty printer for FIX messages
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-color\fR=\fIwhen\fR [default: auto]
Adds colour to the delimiter and = in for FIX fields, auto will colour only when printing directly into a tty
.br

.br
[\fIpossible values: \fRalways, auto, never]
.TP
\fB\-d\fR, \fB\-\-delimiter\fR=\fIdelimiter\fR [default: \\n]
Set delimiter string to print after each FIX field
.TP
\fB\-s\fR, \fB\-\-strip\fR
Strip the whitespace around the = in each field
.TP
\fB\-S\fR, \fB\-\-summary\fR=\fItemplate\fR
Summarise each fix message based on an optional template
.TP
\fB\-t\fR, \fB\-\-tag\fR
Translate all numbers to tag names whether part of a message or not
.TP
\fB\-v\fR, \fB\-\-value\fR
Translate the values of some tags (for Side: 1 \-> Buy)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fImessage\fR]
FIX message to be parsed, if not provided will look for a message piped through stdin
.SH VERSION
v1.1.1
