[package]
name = "prefix"
version = "1.0.1"
authors = ["Shivix"]
edition = "2021"
description = "A customizable pretty printer for FIX messages"
repository = "https://github.com/Shivix/prefix"
license = "GPL-3.0-only"
exclude = [
    ".gitignore",
    "LICENSE",
]
keywords = [
    "fix",
    "parser",
    "pretty",
    "print",
    "cli",
]
categories = [
    "command-line-utilities",
    "text-processing",
    "visualization",
    "development-tools",
]

[dependencies]
regex = "1.5.5"
clap = { version = "3.1.18", features = ["derive"] }
