use phf::phf_map;

pub const TAGS: [&str; 957] = [
    "",
    "Account",
    "AdvId",
    "AdvRefID",
    "AdvSide",
    "AdvTransType",
    "AvgPx",
    "BeginSeqNo",
    "BeginString",
    "BodyLength",
    "CheckSum",
    "ClOrdID",
    "Commission",
    "CommType",
    "CumQty",
    "Currency",
    "EndSeqNo",
    "ExecID",
    "ExecInst",
    "ExecRefID",
    "ExecTransType",
    "HandlInst",
    "SecurityIDSource",
    "IOIID",
    "IOIOthSvc",
    "IOIQltyInd",
    "IOIRefID",
    "IOIQty",
    "IOITransType",
    "LastCapacity",
    "LastMkt",
    "LastPx",
    "LastQty",
    "NoLinesOfText",
    "MsgSeqNum",
    "MsgType",
    "NewSeqNo",
    "OrderID",
    "OrderQty",
    "OrdStatus",
    "OrdType",
    "OrigClOrdID",
    "OrigTime",
    "PossDupFlag",
    "Price",
    "RefSeqNum",
    "RelatdSym",
    "Rule80A",
    "SecurityID",
    "SenderCompID",
    "SenderSubID",
    "SendingDate",
    "SendingTime",
    "Quantity",
    "Side",
    "Symbol",
    "TargetCompID",
    "TargetSubID",
    "Text",
    "TimeInForce",
    "TransactTime",
    "Urgency",
    "ValidUntilTime",
    "SettlType",
    "SettlDate",
    "SymbolSfx",
    "ListID",
    "ListSeqNo",
    "TotNoOrders",
    "ListExecInst",
    "AllocID",
    "AllocTransType",
    "RefAllocID",
    "NoOrders",
    "AvgPxPrecision",
    "TradeDate",
    "ExecBroker",
    "PositionEffect",
    "NoAllocs",
    "AllocAccount",
    "AllocQty",
    "ProcessCode",
    "NoRpts",
    "RptSeq",
    "CxlQty",
    "NoDlvyInst",
    "DlvyInst",
    "AllocStatus",
    "AllocRejCode",
    "Signature",
    "SecureDataLen",
    "SecureData",
    "BrokerOfCredit",
    "SignatureLength",
    "EmailType",
    "RawDataLength",
    "RawData",
    "PossResend",
    "EncryptMethod",
    "StopPx",
    "ExDestination",
    "",
    "CxlRejReason",
    "OrdRejReason",
    "IOIQualifier",
    "WaveNo",
    "Issuer",
    "SecurityDesc",
    "HeartBtInt",
    "ClientID",
    "MinQty",
    "MaxFloor",
    "TestReqID",
    "ReportToExch",
    "LocateReqd",
    "OnBehalfOfCompID",
    "OnBehalfOfSubID",
    "QuoteID",
    "NetMoney",
    "SettlCurrAmt",
    "SettlCurrency",
    "ForexReq",
    "OrigSendingTime",
    "GapFillFlag",
    "NoExecs",
    "CxlType",
    "ExpireTime",
    "DKReason",
    "DeliverToCompID",
    "DeliverToSubID",
    "IOINaturalFlag",
    "QuoteReqID",
    "BidPx",
    "OfferPx",
    "BidSize",
    "OfferSize",
    "NoMiscFees",
    "MiscFeeAmt",
    "MiscFeeCurr",
    "MiscFeeType",
    "PrevClosePx",
    "ResetSeqNumFlag",
    "SenderLocationID",
    "TargetLocationID",
    "OnBehalfOfLocationID",
    "DeliverToLocationID",
    "NoRelatedSym",
    "Subject",
    "Headline",
    "URLLink",
    "ExecType",
    "LeavesQty",
    "CashOrderQty",
    "AllocAvgPx",
    "AllocNetMoney",
    "SettlCurrFxRate",
    "SettlCurrFxRateCalc",
    "NumDaysInterest",
    "AccruedInterestRate",
    "AccruedInterestAmt",
    "SettlInstMode",
    "AllocText",
    "SettlInstID",
    "SettlInstTransType",
    "EmailThreadID",
    "SettlInstSource",
    "SettlLocation",
    "SecurityType",
    "EffectiveTime",
    "StandInstDbType",
    "StandInstDbName",
    "StandInstDbID",
    "SettlDeliveryType",
    "SettlDepositoryCode",
    "SettlBrkrCode",
    "SettlInstCode",
    "SecuritySettlAgentName",
    "SecuritySettlAgentCode",
    "SecuritySettlAgentAcctNum",
    "SecuritySettlAgentAcctName",
    "SecuritySettlAgentContactName",
    "SecuritySettlAgentContactPhone",
    "CashSettlAgentName",
    "CashSettlAgentCode",
    "CashSettlAgentAcctNum",
    "CashSettlAgentAcctName",
    "CashSettlAgentContactName",
    "CashSettlAgentContactPhone",
    "BidSpotRate",
    "BidForwardPoints",
    "OfferSpotRate",
    "OfferForwardPoints",
    "OrderQty2",
    "SettlDate2",
    "LastSpotRate",
    "LastForwardPoints",
    "AllocLinkID",
    "AllocLinkType",
    "SecondaryOrderID",
    "NoIOIQualifiers",
    "MaturityMonthYear",
    "PutOrCall",
    "StrikePrice",
    "CoveredOrUncovered",
    "CustomerOrFirm",
    "MaturityDay",
    "OptAttribute",
    "SecurityExchange",
    "NotifyBrokerOfCredit",
    "AllocHandlInst",
    "MaxShow",
    "PegOffsetValue",
    "XmlDataLen",
    "XmlData",
    "SettlInstRefID",
    "NoRoutingIDs",
    "RoutingType",
    "RoutingID",
    "Spread",
    "Benchmark",
    "BenchmarkCurveCurrency",
    "BenchmarkCurveName",
    "BenchmarkCurvePoint",
    "CouponRate",
    "CouponPaymentDate",
    "IssueDate",
    "RepurchaseTerm",
    "RepurchaseRate",
    "Factor",
    "TradeOriginationDate",
    "ExDate",
    "ContractMultiplier",
    "NoStipulations",
    "StipulationType",
    "StipulationValue",
    "YieldType",
    "Yield",
    "TotalTakedown",
    "Concession",
    "RepoCollateralSecurityType",
    "RedemptionDate",
    "UnderlyingCouponPaymentDate",
    "UnderlyingIssueDate",
    "UnderlyingRepoCollateralSecurityType",
    "UnderlyingRepurchaseTerm",
    "UnderlyingRepurchaseRate",
    "UnderlyingFactor",
    "UnderlyingRedemptionDate",
    "LegCouponPaymentDate",
    "LegIssueDate",
    "LegRepoCollateralSecurityType",
    "LegRepurchaseTerm",
    "LegRepurchaseRate",
    "LegFactor",
    "LegRedemptionDate",
    "CreditRating",
    "UnderlyingCreditRating",
    "LegCreditRating",
    "TradedFlatSwitch",
    "BasisFeatureDate",
    "BasisFeaturePrice",
    "",
    "MDReqID",
    "SubscriptionRequestType",
    "MarketDepth",
    "MDUpdateType",
    "AggregatedBook",
    "NoMDEntryTypes",
    "NoMDEntries",
    "MDEntryType",
    "MDEntryPx",
    "MDEntrySize",
    "MDEntryDate",
    "MDEntryTime",
    "TickDirection",
    "MDMkt",
    "QuoteCondition",
    "TradeCondition",
    "MDEntryID",
    "MDUpdateAction",
    "MDEntryRefID",
    "MDReqRejReason",
    "MDEntryOriginator",
    "LocationID",
    "DeskID",
    "DeleteReason",
    "OpenCloseSettlFlag",
    "SellerDays",
    "MDEntryBuyer",
    "MDEntrySeller",
    "MDEntryPositionNo",
    "FinancialStatus",
    "CorporateAction",
    "DefBidSize",
    "DefOfferSize",
    "NoQuoteEntries",
    "NoQuoteSets",
    "QuoteStatus",
    "QuoteCancelType",
    "QuoteEntryID",
    "QuoteRejectReason",
    "QuoteResponseLevel",
    "QuoteSetID",
    "QuoteRequestType",
    "TotNoQuoteEntries",
    "UnderlyingSecurityIDSource",
    "UnderlyingIssuer",
    "UnderlyingSecurityDesc",
    "UnderlyingSecurityExchange",
    "UnderlyingSecurityID",
    "UnderlyingSecurityType",
    "UnderlyingSymbol",
    "UnderlyingSymbolSfx",
    "UnderlyingMaturityMonthYear",
    "UnderlyingMaturityDay",
    "UnderlyingPutOrCall",
    "UnderlyingStrikePrice",
    "UnderlyingOptAttribute",
    "UnderlyingCurrency",
    "RatioQty",
    "SecurityReqID",
    "SecurityRequestType",
    "SecurityResponseID",
    "SecurityResponseType",
    "SecurityStatusReqID",
    "UnsolicitedIndicator",
    "SecurityTradingStatus",
    "HaltReason",
    "InViewOfCommon",
    "DueToRelated",
    "BuyVolume",
    "SellVolume",
    "HighPx",
    "LowPx",
    "Adjustment",
    "TradSesReqID",
    "TradingSessionID",
    "ContraTrader",
    "TradSesMethod",
    "TradSesMode",
    "TradSesStatus",
    "TradSesStartTime",
    "TradSesOpenTime",
    "TradSesPreCloseTime",
    "TradSesCloseTime",
    "TradSesEndTime",
    "NumberOfOrders",
    "MessageEncoding",
    "EncodedIssuerLen",
    "EncodedIssuer",
    "EncodedSecurityDescLen",
    "EncodedSecurityDesc",
    "EncodedListExecInstLen",
    "EncodedListExecInst",
    "EncodedTextLen",
    "EncodedText",
    "EncodedSubjectLen",
    "EncodedSubject",
    "EncodedHeadlineLen",
    "EncodedHeadline",
    "EncodedAllocTextLen",
    "EncodedAllocText",
    "EncodedUnderlyingIssuerLen",
    "EncodedUnderlyingIssuer",
    "EncodedUnderlyingSecurityDescLen",
    "EncodedUnderlyingSecurityDesc",
    "AllocPrice",
    "QuoteSetValidUntilTime",
    "QuoteEntryRejectReason",
    "LastMsgSeqNumProcessed",
    "OnBehalfOfSendingTime",
    "RefTagID",
    "RefMsgType",
    "SessionRejectReason",
    "BidRequestTransType",
    "ContraBroker",
    "ComplianceID",
    "SolicitedFlag",
    "ExecRestatementReason",
    "BusinessRejectRefID",
    "BusinessRejectReason",
    "GrossTradeAmt",
    "NoContraBrokers",
    "MaxMessageSize",
    "NoMsgTypes",
    "MsgDirection",
    "NoTradingSessions",
    "TotalVolumeTraded",
    "DiscretionInst",
    "DiscretionOffsetValue",
    "BidID",
    "ClientBidID",
    "ListName",
    "TotNoRelatedSym",
    "BidType",
    "NumTickets",
    "SideValue1",
    "SideValue2",
    "NoBidDescriptors",
    "BidDescriptorType",
    "BidDescriptor",
    "SideValueInd",
    "LiquidityPctLow",
    "LiquidityPctHigh",
    "LiquidityValue",
    "EFPTrackingError",
    "FairValue",
    "OutsideIndexPct",
    "ValueOfFutures",
    "LiquidityIndType",
    "WtAverageLiquidity",
    "ExchangeForPhysical",
    "OutMainCntryUIndex",
    "CrossPercent",
    "ProgRptReqs",
    "ProgPeriodInterval",
    "IncTaxInd",
    "NumBidders",
    "BidTradeType",
    "BasisPxType",
    "NoBidComponents",
    "Country",
    "TotNoStrikes",
    "PriceType",
    "DayOrderQty",
    "DayCumQty",
    "DayAvgPx",
    "GTBookingInst",
    "NoStrikes",
    "ListStatusType",
    "NetGrossInd",
    "ListOrderStatus",
    "ExpireDate",
    "ListExecInstType",
    "CxlRejResponseTo",
    "UnderlyingCouponRate",
    "UnderlyingContractMultiplier",
    "ContraTradeQty",
    "ContraTradeTime",
    "ClearingFirm",
    "ClearingAccount",
    "LiquidityNumSecurities",
    "MultiLegReportingType",
    "StrikeTime",
    "ListStatusText",
    "EncodedListStatusTextLen",
    "EncodedListStatusText",
    "PartyIDSource",
    "PartyID",
    "TotalVolumeTradedDate",
    "TotalVolumeTradedTime",
    "NetChgPrevDay",
    "PartyRole",
    "NoPartyIDs",
    "NoSecurityAltID",
    "SecurityAltID",
    "SecurityAltIDSource",
    "NoUnderlyingSecurityAltID",
    "UnderlyingSecurityAltID",
    "UnderlyingSecurityAltIDSource",
    "Product",
    "CFICode",
    "UnderlyingProduct",
    "UnderlyingCFICode",
    "TestMessageIndicator",
    "QuantityType",
    "BookingRefID",
    "IndividualAllocID",
    "RoundingDirection",
    "RoundingModulus",
    "CountryOfIssue",
    "StateOrProvinceOfIssue",
    "LocaleOfIssue",
    "NoRegistDtls",
    "MailingDtls",
    "InvestorCountryOfResidence",
    "PaymentRef",
    "DistribPaymentMethod",
    "CashDistribCurr",
    "CommCurrency",
    "CancellationRights",
    "MoneyLaunderingStatus",
    "MailingInst",
    "TransBkdTime",
    "ExecPriceType",
    "ExecPriceAdjustment",
    "DateOfBirth",
    "TradeReportTransType",
    "CardHolderName",
    "CardNumber",
    "CardExpDate",
    "CardIssNum",
    "PaymentMethod",
    "RegistAcctType",
    "Designation",
    "TaxAdvantageType",
    "RegistRejReasonText",
    "FundRenewWaiv",
    "CashDistribAgentName",
    "CashDistribAgentCode",
    "CashDistribAgentAcctNumber",
    "CashDistribPayRef",
    "CashDistribAgentAcctName",
    "CardStartDate",
    "PaymentDate",
    "PaymentRemitterID",
    "RegistStatus",
    "RegistRejReasonCode",
    "RegistRefID",
    "RegistDtls",
    "NoDistribInsts",
    "RegistEmail",
    "DistribPercentage",
    "RegistID",
    "RegistTransType",
    "ExecValuationPoint",
    "OrderPercent",
    "OwnershipType",
    "NoContAmts",
    "ContAmtType",
    "ContAmtValue",
    "ContAmtCurr",
    "OwnerType",
    "PartySubID",
    "NestedPartyID",
    "NestedPartyIDSource",
    "SecondaryClOrdID",
    "SecondaryExecID",
    "OrderCapacity",
    "OrderRestrictions",
    "MassCancelRequestType",
    "MassCancelResponse",
    "MassCancelRejectReason",
    "TotalAffectedOrders",
    "NoAffectedOrders",
    "AffectedOrderID",
    "AffectedSecondaryOrderID",
    "QuoteType",
    "NestedPartyRole",
    "NoNestedPartyIDs",
    "TotalAccruedInterestAmt",
    "MaturityDate",
    "UnderlyingMaturityDate",
    "InstrRegistry",
    "CashMargin",
    "NestedPartySubID",
    "Scope",
    "MDImplicitDelete",
    "CrossID",
    "CrossType",
    "CrossPrioritization",
    "OrigCrossID",
    "NoSides",
    "Username",
    "Password",
    "NoLegs",
    "LegCurrency",
    "TotNoSecurityTypes",
    "NoSecurityTypes",
    "SecurityListRequestType",
    "SecurityRequestResult",
    "RoundLot",
    "MinTradeVol",
    "MultiLegRptTypeReq",
    "LegPositionEffect",
    "LegCoveredOrUncovered",
    "LegPrice",
    "TradSesStatusRejReason",
    "TradeRequestID",
    "TradeRequestType",
    "PreviouslyReported",
    "TradeReportID",
    "TradeReportRefID",
    "MatchStatus",
    "MatchType",
    "OddLot",
    "NoClearingInstructions",
    "ClearingInstruction",
    "TradeInputSource",
    "TradeInputDevice",
    "NoDates",
    "AccountType",
    "CustOrderCapacity",
    "ClOrdLinkID",
    "MassStatusReqID",
    "MassStatusReqType",
    "OrigOrdModTime",
    "LegSettlType",
    "LegSettlDate",
    "DayBookingInst",
    "BookingUnit",
    "PreallocMethod",
    "UnderlyingCountryOfIssue",
    "UnderlyingStateOrProvinceOfIssue",
    "UnderlyingLocaleOfIssue",
    "UnderlyingInstrRegistry",
    "LegCountryOfIssue",
    "LegStateOrProvinceOfIssue",
    "LegLocaleOfIssue",
    "LegInstrRegistry",
    "LegSymbol",
    "LegSymbolSfx",
    "LegSecurityID",
    "LegSecurityIDSource",
    "NoLegSecurityAltID",
    "LegSecurityAltID",
    "LegSecurityAltIDSource",
    "LegProduct",
    "LegCFICode",
    "LegSecurityType",
    "LegMaturityMonthYear",
    "LegMaturityDate",
    "LegStrikePrice",
    "LegOptAttribute",
    "LegContractMultiplier",
    "LegCouponRate",
    "LegSecurityExchange",
    "LegIssuer",
    "EncodedLegIssuerLen",
    "EncodedLegIssuer",
    "LegSecurityDesc",
    "EncodedLegSecurityDescLen",
    "EncodedLegSecurityDesc",
    "LegRatioQty",
    "LegSide",
    "TradingSessionSubID",
    "AllocType",
    "NoHops",
    "HopCompID",
    "HopSendingTime",
    "HopRefID",
    "MidPx",
    "BidYield",
    "MidYield",
    "OfferYield",
    "ClearingFeeIndicator",
    "WorkingIndicator",
    "LegLastPx",
    "PriorityIndicator",
    "PriceImprovement",
    "Price2",
    "LastForwardPoints2",
    "BidForwardPoints2",
    "OfferForwardPoints2",
    "RFQReqID",
    "MktBidPx",
    "MktOfferPx",
    "MinBidSize",
    "MinOfferSize",
    "QuoteStatusReqID",
    "LegalConfirm",
    "UnderlyingLastPx",
    "UnderlyingLastQty",
    "SecDefStatus",
    "LegRefID",
    "ContraLegRefID",
    "SettlCurrBidFxRate",
    "SettlCurrOfferFxRate",
    "QuoteRequestRejectReason",
    "SideComplianceID",
    "AcctIDSource",
    "AllocAcctIDSource",
    "BenchmarkPrice",
    "BenchmarkPriceType",
    "ConfirmID",
    "ConfirmStatus",
    "ConfirmTransType",
    "ContractSettlMonth",
    "DeliveryForm",
    "LastParPx",
    "NoLegAllocs",
    "LegAllocAccount",
    "LegIndividualAllocID",
    "LegAllocQty",
    "LegAllocAcctIDSource",
    "LegSettlCurrency",
    "LegBenchmarkCurveCurrency",
    "LegBenchmarkCurveName",
    "LegBenchmarkCurvePoint",
    "LegBenchmarkPrice",
    "LegBenchmarkPriceType",
    "LegBidPx",
    "LegIOIQty",
    "NoLegStipulations",
    "LegOfferPx",
    "LegOrderQty",
    "LegPriceType",
    "LegQty",
    "LegStipulationType",
    "LegStipulationValue",
    "LegSwapType",
    "Pool",
    "QuotePriceType",
    "QuoteRespID",
    "QuoteRespType",
    "QuoteQualifier",
    "YieldRedemptionDate",
    "YieldRedemptionPrice",
    "YieldRedemptionPriceType",
    "BenchmarkSecurityID",
    "ReversalIndicator",
    "YieldCalcDate",
    "NoPositions",
    "PosType",
    "LongQty",
    "ShortQty",
    "PosQtyStatus",
    "PosAmtType",
    "PosAmt",
    "PosTransType",
    "PosReqID",
    "NoUnderlyings",
    "PosMaintAction",
    "OrigPosReqRefID",
    "PosMaintRptRefID",
    "ClearingBusinessDate",
    "SettlSessID",
    "SettlSessSubID",
    "AdjustmentType",
    "ContraryInstructionIndicator",
    "PriorSpreadIndicator",
    "PosMaintRptID",
    "PosMaintStatus",
    "PosMaintResult",
    "PosReqType",
    "ResponseTransportType",
    "ResponseDestination",
    "TotalNumPosReports",
    "PosReqResult",
    "PosReqStatus",
    "SettlPrice",
    "SettlPriceType",
    "UnderlyingSettlPrice",
    "UnderlyingSettlPriceType",
    "PriorSettlPrice",
    "NoQuoteQualifiers",
    "AllocSettlCurrency",
    "AllocSettlCurrAmt",
    "InterestAtMaturity",
    "LegDatedDate",
    "LegPool",
    "AllocInterestAtMaturity",
    "AllocAccruedInterestAmt",
    "DeliveryDate",
    "AssignmentMethod",
    "AssignmentUnit",
    "OpenInterest",
    "ExerciseMethod",
    "TotNumTradeReports",
    "TradeRequestResult",
    "TradeRequestStatus",
    "TradeReportRejectReason",
    "SideMultiLegReportingType",
    "NoPosAmt",
    "AutoAcceptIndicator",
    "AllocReportID",
    "NoNested2PartyIDs",
    "Nested2PartyID",
    "Nested2PartyIDSource",
    "Nested2PartyRole",
    "Nested2PartySubID",
    "BenchmarkSecurityIDSource",
    "SecuritySubType",
    "UnderlyingSecuritySubType",
    "LegSecuritySubType",
    "AllowableOneSidednessPct",
    "AllowableOneSidednessValue",
    "AllowableOneSidednessCurr",
    "NoTrdRegTimestamps",
    "TrdRegTimestamp",
    "TrdRegTimestampType",
    "TrdRegTimestampOrigin",
    "ConfirmRefID",
    "ConfirmType",
    "ConfirmRejReason",
    "BookingType",
    "IndividualAllocRejCode",
    "SettlInstMsgID",
    "NoSettlInst",
    "LastUpdateTime",
    "AllocSettlInstType",
    "NoSettlPartyIDs",
    "SettlPartyID",
    "SettlPartyIDSource",
    "SettlPartyRole",
    "SettlPartySubID",
    "SettlPartySubIDType",
    "DlvyInstType",
    "TerminationType",
    "NextExpectedMsgSeqNum",
    "OrdStatusReqID",
    "SettlInstReqID",
    "SettlInstReqRejCode",
    "SecondaryAllocID",
    "AllocReportType",
    "AllocReportRefID",
    "AllocCancReplaceReason",
    "CopyMsgIndicator",
    "AllocAccountType",
    "OrderAvgPx",
    "OrderBookingQty",
    "NoSettlPartySubIDs",
    "NoPartySubIDs",
    "PartySubIDType",
    "NoNestedPartySubIDs",
    "NestedPartySubIDType",
    "NoNested2PartySubIDs",
    "Nested2PartySubIDType",
    "AllocIntermedReqType",
    "",
    "UnderlyingPx",
    "PriceDelta",
    "ApplQueueMax",
    "ApplQueueDepth",
    "ApplQueueResolution",
    "ApplQueueAction",
    "NoAltMDSource",
    "AltMDSourceID",
    "SecondaryTradeReportID",
    "AvgPxIndicator",
    "TradeLinkID",
    "OrderInputDevice",
    "UnderlyingTradingSessionID",
    "UnderlyingTradingSessionSubID",
    "TradeLegRefID",
    "ExchangeRule",
    "TradeAllocIndicator",
    "ExpirationCycle",
    "TrdType",
    "TrdSubType",
    "TransferReason",
    "AsgnReqID",
    "TotNumAssignmentReports",
    "AsgnRptID",
    "ThresholdAmount",
    "PegMoveType",
    "PegOffsetType",
    "PegLimitType",
    "PegRoundDirection",
    "PeggedPrice",
    "PegScope",
    "DiscretionMoveType",
    "DiscretionOffsetType",
    "DiscretionLimitType",
    "DiscretionRoundDirection",
    "DiscretionPrice",
    "DiscretionScope",
    "TargetStrategy",
    "TargetStrategyParameters",
    "ParticipationRate",
    "TargetStrategyPerformance",
    "LastLiquidityInd",
    "PublishTrdIndicator",
    "ShortSaleReason",
    "QtyType",
    "SecondaryTrdType",
    "TradeReportType",
    "AllocNoOrdersType",
    "SharedCommission",
    "ConfirmReqID",
    "AvgParPx",
    "ReportedPx",
    "NoCapacities",
    "OrderCapacityQty",
    "NoEvents",
    "EventType",
    "EventDate",
    "EventPx",
    "EventText",
    "PctAtRisk",
    "NoInstrAttrib",
    "InstrAttribType",
    "InstrAttribValue",
    "DatedDate",
    "InterestAccrualDate",
    "CPProgram",
    "CPRegType",
    "UnderlyingCPProgram",
    "UnderlyingCPRegType",
    "UnderlyingQty",
    "TrdMatchID",
    "SecondaryTradeReportRefID",
    "UnderlyingDirtyPrice",
    "UnderlyingEndPrice",
    "UnderlyingStartValue",
    "UnderlyingCurrentValue",
    "UnderlyingEndValue",
    "NoUnderlyingStips",
    "UnderlyingStipType",
    "UnderlyingStipValue",
    "MaturityNetMoney",
    "MiscFeeBasis",
    "TotNoAllocs",
    "LastFragment",
    "CollReqID",
    "CollAsgnReason",
    "CollInquiryQualifier",
    "NoTrades",
    "MarginRatio",
    "MarginExcess",
    "TotalNetValue",
    "CashOutstanding",
    "CollAsgnID",
    "CollAsgnTransType",
    "CollRespID",
    "CollAsgnRespType",
    "CollAsgnRejectReason",
    "CollAsgnRefID",
    "CollRptID",
    "CollInquiryID",
    "CollStatus",
    "TotNumReports",
    "LastRptRequested",
    "AgreementDesc",
    "AgreementID",
    "AgreementDate",
    "StartDate",
    "EndDate",
    "AgreementCurrency",
    "DeliveryType",
    "EndAccruedInterestAmt",
    "StartCash",
    "EndCash",
    "UserRequestID",
    "UserRequestType",
    "NewPassword",
    "UserStatus",
    "UserStatusText",
    "StatusValue",
    "StatusText",
    "RefCompID",
    "RefSubID",
    "NetworkResponseID",
    "NetworkRequestID",
    "LastNetworkResponseID",
    "NetworkRequestType",
    "NoCompIDs",
    "NetworkStatusResponseType",
    "NoCollInquiryQualifier",
    "TrdRptStatus",
    "AffirmStatus",
    "UnderlyingStrikeCurrency",
    "LegStrikeCurrency",
    "TimeBracket",
    "CollAction",
    "CollInquiryStatus",
    "CollInquiryResult",
    "StrikeCurrency",
    "NoNested3PartyIDs",
    "Nested3PartyID",
    "Nested3PartyIDSource",
    "Nested3PartyRole",
    "NoNested3PartySubIDs",
    "Nested3PartySubID",
    "Nested3PartySubIDType",
    "LegContractSettlMonth",
    "LegInterestAccrualDate",
];

pub static VALUES: phf::Map<&'static str, &'static str> = phf_map! {
    "4-B" => "Buy",
    "4-S" => "Sell",
    "4-X" => "Cross",
    "4-T" => "Trade",
    "5-N" => "New",
    "5-C" => "Cancel",
    "5-R" => "Replace",
    "13-1" => "PerUnit",
    "13-2" => "Percent",
    "13-3" => "Absolute",
    "13-4" => "PercentageWaivedCashDiscount",
    "13-5" => "PercentageWaivedEnhancedUnits",
    "13-6" => "PointsPerBondOrContract",
    "18-1" => "NotHeld",
    "18-2" => "Work",
    "18-3" => "GoAlong",
    "18-4" => "OverTheDay",
    "18-5" => "Held",
    "18-6" => "ParticipateDoNotInitiate",
    "18-7" => "StrictScale",
    "18-8" => "TryToScale",
    "18-9" => "StayOnBidSide",
    "18-0" => "StayOnOfferSide",
    "18-A" => "NoCross",
    "18-B" => "OkToCross",
    "18-C" => "CallFirst",
    "18-D" => "PercentOfVolume",
    "18-E" => "DoNotIncrease",
    "18-F" => "DoNotReduce",
    "18-G" => "AllOrNone",
    "18-H" => "ReinstateOnSystemFailure",
    "18-I" => "InstitutionsOnly",
    "18-J" => "ReinstateOnTradingHalt",
    "18-K" => "CancelOnTradingHalt",
    "18-L" => "LastPeg",
    "18-M" => "MidPricePeg",
    "18-N" => "NonNegotiable",
    "18-O" => "OpeningPeg",
    "18-P" => "MarketPeg",
    "18-Q" => "CancelOnSystemFailure",
    "18-R" => "PrimaryPeg",
    "18-S" => "Suspend",
    "18-U" => "CustomerDisplayInstruction",
    "18-V" => "Netting",
    "18-W" => "PegToVwap",
    "18-X" => "TradeAlong",
    "18-Y" => "TryToStop",
    "18-Z" => "CancelIfNotBest",
    "18-a" => "TrailingStopPeg",
    "18-b" => "StrictLimit",
    "18-c" => "IgnorePriceValidityChecks",
    "18-d" => "PegToLimitPrice",
    "18-e" => "WorkToTargetStrategy",
    "21-1" => "AutomatedExecutionNoIntervention",
    "21-2" => "AutomatedExecutionInterventionOk",
    "21-3" => "ManualOrder",
    "22-1" => "Cusip",
    "22-2" => "Sedol",
    "22-3" => "Quik",
    "22-4" => "IsinNumber",
    "22-5" => "RicCode",
    "22-6" => "IsoCurrencyCode",
    "22-7" => "IsoCountryCode",
    "22-8" => "ExchangeSymbol",
    "22-9" => "ConsolidatedTapeAssociation",
    "22-A" => "BloombergSymbol",
    "22-B" => "Wertpapier",
    "22-C" => "Dutch",
    "22-D" => "Valoren",
    "22-E" => "Sicovam",
    "22-F" => "Belgian",
    "22-G" => "Common",
    "22-H" => "ClearingHouse",
    "22-I" => "IsdaFpMlSpecification",
    "22-J" => "OptionPriceReportingAuthority",
    "25-L" => "Low",
    "25-M" => "Medium",
    "25-H" => "High",
    "27-S" => "Small",
    "27-M" => "Medium",
    "27-L" => "Large",
    "28-N" => "New",
    "28-C" => "Cancel",
    "28-R" => "Replace",
    "29-1" => "Agent",
    "29-2" => "CrossAsAgent",
    "29-3" => "CrossAsPrincipal",
    "29-4" => "Principal",
    "35-0" => "Heartbeat",
    "35-1" => "TestRequest",
    "35-2" => "ResendRequest",
    "35-3" => "Reject",
    "35-4" => "SequenceReset",
    "35-5" => "Logout",
    "35-6" => "Ioi",
    "35-7" => "Advertisement",
    "35-8" => "ExecutionReport",
    "35-9" => "OrderCancelReject",
    "35-A" => "Logon",
    "35-B" => "News",
    "35-C" => "Email",
    "35-D" => "NewOrderSingle",
    "35-E" => "NewOrderList",
    "35-F" => "OrderCancelRequest",
    "35-G" => "OrderCancelReplaceRequest",
    "35-H" => "OrderStatusRequest",
    "35-J" => "AllocationInstruction",
    "35-K" => "ListCancelRequest",
    "35-L" => "ListExecute",
    "35-M" => "ListStatusRequest",
    "35-N" => "ListStatus",
    "35-P" => "AllocationInstructionAck",
    "35-Q" => "DontKnowTrade",
    "35-R" => "QuoteRequest",
    "35-S" => "Quote",
    "35-T" => "SettlementInstructions",
    "35-V" => "MarketDataRequest",
    "35-W" => "MarketDataSnapshotFullRefresh",
    "35-X" => "MarketDataIncrementalRefresh",
    "35-Y" => "MarketDataRequestReject",
    "35-Z" => "QuoteCancel",
    "35-a" => "QuoteStatusRequest",
    "35-b" => "MassQuoteAcknowledgement",
    "35-c" => "SecurityDefinitionRequest",
    "35-d" => "SecurityDefinition",
    "35-e" => "SecurityStatusRequest",
    "35-f" => "SecurityStatus",
    "35-g" => "TradingSessionStatusRequest",
    "35-h" => "TradingSessionStatus",
    "35-i" => "MassQuote",
    "35-j" => "BusinessMessageReject",
    "35-k" => "BidRequest",
    "35-l" => "BidResponse",
    "35-m" => "ListStrikePrice",
    "35-n" => "XmlNonFix",
    "35-o" => "RegistrationInstructions",
    "35-p" => "RegistrationInstructionsResponse",
    "35-q" => "OrderMassCancelRequest",
    "35-r" => "OrderMassCancelReport",
    "35-s" => "NewOrderCross",
    "35-t" => "CrossOrderCancelReplaceRequest",
    "35-u" => "CrossOrderCancelRequest",
    "35-v" => "SecurityTypeRequest",
    "35-w" => "SecurityTypes",
    "35-x" => "SecurityListRequest",
    "35-y" => "SecurityList",
    "35-z" => "DerivativeSecurityListRequest",
    "35-AA" => "DerivativeSecurityList",
    "35-AB" => "NewOrderMultileg",
    "35-AC" => "MultilegOrderCancelReplace",
    "35-AD" => "TradeCaptureReportRequest",
    "35-AE" => "TradeCaptureReport",
    "35-AF" => "OrderMassStatusRequest",
    "35-AG" => "QuoteRequestReject",
    "35-AH" => "RfqRequest",
    "35-AI" => "QuoteStatusReport",
    "35-AJ" => "QuoteResponse",
    "35-AK" => "Confirmation",
    "35-AL" => "PositionMaintenanceRequest",
    "35-AM" => "PositionMaintenanceReport",
    "35-AN" => "RequestForPositions",
    "35-AO" => "RequestForPositionsAck",
    "35-AP" => "PositionReport",
    "35-AQ" => "TradeCaptureReportRequestAck",
    "35-AR" => "TradeCaptureReportAck",
    "35-AS" => "AllocationReport",
    "35-AT" => "AllocationReportAck",
    "35-AU" => "ConfirmationAck",
    "35-AV" => "SettlementInstructionRequest",
    "35-AW" => "AssignmentReport",
    "35-AX" => "CollateralRequest",
    "35-AY" => "CollateralAssignment",
    "35-AZ" => "CollateralResponse",
    "35-BA" => "CollateralReport",
    "35-BB" => "CollateralInquiry",
    "35-BC" => "NetworkCounterpartySystemStatusRequest",
    "35-BD" => "NetworkCounterpartySystemStatusResponse",
    "35-BE" => "UserRequest",
    "35-BF" => "UserResponse",
    "35-BG" => "CollateralInquiryAck",
    "35-BH" => "ConfirmationRequest",
    "39-0" => "New",
    "39-1" => "PartiallyFilled",
    "39-2" => "Filled",
    "39-3" => "DoneForDay",
    "39-4" => "Canceled",
    "39-6" => "PendingCancel",
    "39-7" => "Stopped",
    "39-8" => "Rejected",
    "39-9" => "Suspended",
    "39-A" => "PendingNew",
    "39-B" => "Calculated",
    "39-C" => "Expired",
    "39-D" => "AcceptedForBidding",
    "39-E" => "PendingReplace",
    "40-1" => "Market",
    "40-2" => "Limit",
    "40-3" => "Stop",
    "40-4" => "StopLimit",
    "40-6" => "WithOrWithout",
    "40-7" => "LimitOrBetter",
    "40-8" => "LimitWithOrWithout",
    "40-9" => "OnBasis",
    "40-D" => "PreviouslyQuoted",
    "40-E" => "PreviouslyIndicated",
    "40-G" => "ForexSwap",
    "40-I" => "Funari",
    "40-J" => "MarketIfTouched",
    "40-K" => "MarketWithLeftOverAsLimit",
    "40-L" => "PreviousFundValuationPoint",
    "40-M" => "NextFundValuationPoint",
    "40-P" => "Pegged",
    "43-Y" => "Yes",
    "43-N" => "No",
    "54-1" => "Buy",
    "54-2" => "Sell",
    "54-3" => "BuyMinus",
    "54-4" => "SellPlus",
    "54-5" => "SellShort",
    "54-6" => "SellShortExempt",
    "54-7" => "Undisclosed",
    "54-8" => "Cross",
    "54-9" => "CrossShort",
    "54-A" => "CrossShortExempt",
    "54-B" => "AsDefined",
    "54-C" => "Opposite",
    "54-D" => "Subscribe",
    "54-E" => "Redeem",
    "54-F" => "Lend",
    "54-G" => "Borrow",
    "59-0" => "Day",
    "59-1" => "GoodTillCancel",
    "59-2" => "AtTheOpening",
    "59-3" => "ImmediateOrCancel",
    "59-4" => "FillOrKill",
    "59-5" => "GoodTillCrossing",
    "59-6" => "GoodTillDate",
    "59-7" => "AtTheClose",
    "61-0" => "Normal",
    "61-1" => "Flash",
    "61-2" => "Background",
    "63-0" => "Regular",
    "63-1" => "Cash",
    "63-2" => "NextDay",
    "63-3" => "TPlus2",
    "63-4" => "TPlus3",
    "63-5" => "TPlus4",
    "63-6" => "Future",
    "63-7" => "WhenAndIfIssued",
    "63-8" => "SellersOption",
    "63-9" => "TPlus5",
    "71-0" => "New",
    "71-1" => "Replace",
    "71-2" => "Cancel",
    "77-O" => "Open",
    "77-C" => "Close",
    "77-R" => "Rolled",
    "77-F" => "Fifo",
    "81-0" => "Regular",
    "81-1" => "SoftDollar",
    "81-2" => "StepIn",
    "81-3" => "StepOut",
    "81-4" => "SoftDollarStepIn",
    "81-5" => "SoftDollarStepOut",
    "81-6" => "PlanSponsor",
    "87-0" => "Accepted",
    "87-1" => "BlockLevelReject",
    "87-2" => "AccountLevelReject",
    "87-3" => "Received",
    "87-4" => "Incomplete",
    "87-5" => "RejectedByIntermediary",
    "88-0" => "UnknownAccount",
    "88-1" => "IncorrectQuantity",
    "88-2" => "IncorrectAveragegPrice",
    "88-3" => "UnknownExecutingBrokerMnemonic",
    "88-4" => "CommissionDifference",
    "88-5" => "UnknownOrderId",
    "88-6" => "UnknownListId",
    "88-7" => "OtherSeeText",
    "88-8" => "IncorrectAllocatedQuantity",
    "88-9" => "CalculationDifference",
    "88-10" => "UnknownOrStaleExecId",
    "88-11" => "MismatchedData",
    "88-12" => "UnknownClOrdId",
    "88-13" => "WarehouseRequestRejected",
    "94-0" => "New",
    "94-1" => "Reply",
    "94-2" => "AdminReply",
    "97-Y" => "Yes",
    "97-N" => "No",
    "98-0" => "None",
    "98-1" => "Pkcs",
    "98-2" => "Des",
    "98-3" => "Pkcsdes",
    "98-4" => "Pgpdes",
    "98-5" => "Pgpdesmd5",
    "98-6" => "Pem",
    "102-0" => "TooLateToCancel",
    "102-1" => "UnknownOrder",
    "102-2" => "BrokerCredit",
    "102-3" => "OrderAlreadyInPendingStatus",
    "102-4" => "UnableToProcessOrderMassCancelRequest",
    "102-5" => "OrigOrdModTime",
    "102-6" => "DuplicateClOrdId",
    "102-99" => "Other",
    "103-0" => "BrokerCredit",
    "103-1" => "UnknownSymbol",
    "103-2" => "ExchangeClosed",
    "103-3" => "OrderExceedsLimit",
    "103-4" => "TooLateToEnter",
    "103-5" => "UnknownOrder",
    "103-6" => "DuplicateOrder",
    "103-7" => "DuplicateOfAVerballyCommunicatedOrder",
    "103-8" => "StaleOrder",
    "103-9" => "TradeAlongRequired",
    "103-10" => "InvalidInvestorId",
    "103-11" => "UnsupportedOrderCharacteristic",
    "103-13" => "IncorrectQuantity",
    "103-14" => "IncorrectAllocatedQuantity",
    "103-15" => "UnknownAccount",
    "103-99" => "Other",
    "104-A" => "AllOrNone",
    "104-B" => "MarketOnClose",
    "104-C" => "AtTheClose",
    "104-D" => "Vwap",
    "104-I" => "InTouchWith",
    "104-L" => "Limit",
    "104-M" => "MoreBehind",
    "104-O" => "AtTheOpen",
    "104-P" => "TakingAPosition",
    "104-Q" => "AtTheMarket",
    "104-R" => "ReadyToTrade",
    "104-S" => "PortfolioShown",
    "104-T" => "ThroughTheDay",
    "104-V" => "Versus",
    "104-W" => "Indication",
    "104-X" => "CrossingOpportunity",
    "104-Y" => "AtTheMidpoint",
    "104-Z" => "PreOpen",
    "113-Y" => "Yes",
    "113-N" => "No",
    "114-Y" => "Yes",
    "114-N" => "No",
    "121-Y" => "Yes",
    "121-N" => "No",
    "123-Y" => "Yes",
    "123-N" => "No",
    "127-A" => "UnknownSymbol",
    "127-B" => "WrongSide",
    "127-C" => "QuantityExceedsOrder",
    "127-D" => "NoMatchingOrder",
    "127-E" => "PriceExceedsLimit",
    "127-F" => "CalculationDifference",
    "127-Z" => "Other",
    "130-Y" => "Yes",
    "130-N" => "No",
    "139-1" => "Regulatory",
    "139-2" => "Tax",
    "139-3" => "LocalCommission",
    "139-4" => "ExchangeFees",
    "139-5" => "Stamp",
    "139-6" => "Levy",
    "139-7" => "Other",
    "139-8" => "Markup",
    "139-9" => "ConsumptionTax",
    "139-10" => "PerTransaction",
    "139-11" => "Conversion",
    "139-12" => "Agent",
    "141-Y" => "Yes",
    "141-N" => "No",
    "150-0" => "New",
    "150-3" => "DoneForDay",
    "150-4" => "Canceled",
    "150-5" => "Replaced",
    "150-6" => "PendingCancel",
    "150-7" => "Stopped",
    "150-8" => "Rejected",
    "150-9" => "Suspended",
    "150-A" => "PendingNew",
    "150-B" => "Calculated",
    "150-C" => "Expired",
    "150-D" => "Restated",
    "150-E" => "PendingReplace",
    "150-F" => "Trade",
    "150-G" => "TradeCorrect",
    "150-H" => "TradeCancel",
    "150-I" => "OrderStatus",
    "156-M" => "Multiply",
    "156-D" => "Divide",
    "160-1" => "StandingInstructionsProvided",
    "160-4" => "SpecificOrderForASingleAccount",
    "160-5" => "RequestReject",
    "163-N" => "New",
    "163-C" => "Cancel",
    "163-R" => "Replace",
    "163-T" => "Restate",
    "165-1" => "BrokerCredit",
    "165-2" => "Institution",
    "165-3" => "Investor",
    "167-EUSUPRA" => "EuroSupranationalCoupons",
    "167-FAC" => "FederalAgencyCoupon",
    "167-FADN" => "FederalAgencyDiscountNote",
    "167-PEF" => "PrivateExportFunding",
    "167-SUPRA" => "UsdSupranationalCoupons",
    "167-CORP" => "CorporateBond",
    "167-CPP" => "CorporatePrivatePlacement",
    "167-CB" => "ConvertibleBond",
    "167-DUAL" => "DualCurrency",
    "167-EUCORP" => "EuroCorporateBond",
    "167-XLINKD" => "IndexedLinked",
    "167-STRUCT" => "StructuredNotes",
    "167-YANK" => "YankeeCorporateBond",
    "167-FOR" => "ForeignExchangeContract",
    "167-CS" => "CommonStock",
    "167-PS" => "PreferredStock",
    "167-BRADY" => "BradyBond",
    "167-EUSOV" => "EuroSovereigns",
    "167-TBOND" => "UsTreasuryBond",
    "167-TINT" => "InterestStripFromAnyBondOrNote",
    "167-TIPS" => "TreasuryInflationProtectedSecurities",
    "167-TCAL" => "PrincipalStripOfACallableBondOrNote",
    "167-TPRN" => "PrincipalStripFromANonCallableBondOrNote",
    "167-UST" => "UsTreasuryNoteOld",
    "167-USTB" => "UsTreasuryBillOld",
    "167-TNOTE" => "UsTreasuryNote",
    "167-TBILL" => "UsTreasuryBill",
    "167-REPO" => "Repurchase",
    "167-FORWARD" => "Forward",
    "167-BUYSELL" => "BuySellback",
    "167-SECLOAN" => "SecuritiesLoan",
    "167-SECPLEDGE" => "SecuritiesPledge",
    "167-TERM" => "TermLoan",
    "167-RVLV" => "RevolverLoan",
    "167-RVLVTRM" => "Revolver",
    "167-BRIDGE" => "BridgeLoan",
    "167-LOFC" => "LetterOfCredit",
    "167-SWING" => "SwingLineFacility",
    "167-DINP" => "DebtorInPossession",
    "167-DEFLTED" => "Defaulted",
    "167-WITHDRN" => "Withdrawn",
    "167-REPLACD" => "Replaced",
    "167-MATURED" => "Matured",
    "167-AMENDED" => "Amended",
    "167-RETIRED" => "Retired",
    "167-BA" => "BankersAcceptance",
    "167-BN" => "BankNotes",
    "167-BOX" => "BillOfExchanges",
    "167-CD" => "CertificateOfDeposit",
    "167-CL" => "CallLoans",
    "167-CP" => "CommercialPaper",
    "167-DN" => "DepositNotes",
    "167-EUCD" => "EuroCertificateOfDeposit",
    "167-EUCP" => "EuroCommercialPaper",
    "167-LQN" => "LiquidityNote",
    "167-MTN" => "MediumTermNotes",
    "167-ONITE" => "Overnight",
    "167-PN" => "PromissoryNote",
    "167-PZFJ" => "PlazosFijos",
    "167-STN" => "ShortTermLoanNote",
    "167-TD" => "TimeDeposit",
    "167-XCN" => "ExtendedCommNote",
    "167-YCD" => "YankeeCertificateOfDeposit",
    "167-ABS" => "AssetBackedSecurities",
    "167-CMBS" => "Corp",
    "167-CMO" => "CollateralizedMortgageObligation",
    "167-IET" => "IoetteMortgage",
    "167-MBS" => "MortgageBackedSecurities",
    "167-MIO" => "MortgageInterestOnly",
    "167-MPO" => "MortgagePrincipalOnly",
    "167-MPP" => "MortgagePrivatePlacement",
    "167-MPT" => "MiscellaneousPassThrough",
    "167-PFAND" => "Pfandbriefe",
    "167-TBA" => "ToBeAnnounced",
    "167-AN" => "OtherAnticipationNotes",
    "167-COFO" => "CertificateOfObligation",
    "167-COFP" => "CertificateOfParticipation",
    "167-GO" => "GeneralObligationBonds",
    "167-MT" => "MandatoryTender",
    "167-RAN" => "RevenueAnticipationNote",
    "167-REV" => "RevenueBonds",
    "167-SPCLA" => "SpecialAssessment",
    "167-SPCLO" => "SpecialObligation",
    "167-SPCLT" => "SpecialTax",
    "167-TAN" => "TaxAnticipationNote",
    "167-TAXA" => "TaxAllocation",
    "167-TECP" => "TaxExemptCommercialPaper",
    "167-TRAN" => "TaxRevenueAnticipationNote",
    "167-VRDN" => "VariableRateDemandNote",
    "167-WAR" => "Warrant",
    "167-MF" => "MutualFund",
    "167-MLEG" => "MultilegInstrument",
    "167-NONE" => "NoSecurityType",
    "167-FUT" => "Future",
    "167-OPT" => "Option",
    "169-0" => "Other",
    "169-1" => "Dtcsid",
    "169-2" => "ThomsonAlert",
    "169-3" => "AGlobalCustodian",
    "169-4" => "AccountNet",
    "172-0" => "Versus",
    "172-1" => "Free",
    "172-2" => "TriParty",
    "172-3" => "HoldInCustody",
    "197-0" => "FxNetting",
    "197-1" => "FxSwap",
    "201-0" => "Put",
    "201-1" => "Call",
    "203-0" => "Covered",
    "203-1" => "Uncovered",
    "208-Y" => "Yes",
    "208-N" => "No",
    "209-1" => "Match",
    "209-2" => "Forward",
    "209-3" => "ForwardAndMatch",
    "216-1" => "TargetFirm",
    "216-2" => "TargetList",
    "216-3" => "BlockFirm",
    "216-4" => "BlockList",
    "233-AMT" => "AlternativeMinimumTax",
    "233-AUTOREINV" => "AutoReinvestment",
    "233-BANKQUAL" => "BankQualified",
    "233-BGNCON" => "BargainConditions",
    "233-COUPON" => "CouponRange",
    "233-CURRENCY" => "IsoCurrencyCode",
    "233-CUSTOMDATE" => "CustomStart",
    "233-GEOG" => "Geographics",
    "233-HAIRCUT" => "ValuationDiscount",
    "233-INSURED" => "Insured",
    "233-ISSUE" => "IssueDate",
    "233-ISSUER" => "Issuer",
    "233-ISSUESIZE" => "IssueSizeRange",
    "233-LOOKBACK" => "LookbackDays",
    "233-LOT" => "ExplicitLotIdentifier",
    "233-LOTVAR" => "LotVariance",
    "233-MAT" => "MaturityYearAndMonth",
    "233-MATURITY" => "MaturityRange",
    "233-MAXSUBS" => "MaximumSubstitutions",
    "233-MINQTY" => "MinimumQuantity",
    "233-MININCR" => "MinimumIncrement",
    "233-MINDNOM" => "MinimumDenomination",
    "233-PAYFREQ" => "PaymentFrequency",
    "233-PIECES" => "NumberOfPieces",
    "233-PMAX" => "PoolsMaximum",
    "233-PPM" => "PoolsPerMillion",
    "233-PPL" => "PoolsPerLot",
    "233-PPT" => "PoolsPerTrade",
    "233-PRICE" => "PriceRange",
    "233-PRICEFREQ" => "PricingFrequency",
    "233-PROD" => "ProductionYear",
    "233-PROTECT" => "CallProtection",
    "233-PURPOSE" => "Purpose",
    "233-PXSOURCE" => "BenchmarkPriceSource",
    "233-RATING" => "RatingSourceAndRange",
    "233-REDEMPTION" => "TypeOfRedemption",
    "233-RESTRICTED" => "Restricted",
    "233-SECTOR" => "MarketSector",
    "233-SECTYPE" => "SecurityTypeIncludedOrExcluded",
    "233-STRUCT" => "Structure",
    "233-SUBSFREQ" => "SubstitutionsFrequency",
    "233-SUBSLEFT" => "SubstitutionsLeft",
    "233-TEXT" => "FreeformText",
    "233-TRDVAR" => "TradeVariance",
    "233-WAC" => "WeightedAverageCoupon",
    "233-WAL" => "WeightedAverageLifeCoupon",
    "233-WALA" => "WeightedAverageLoanAge",
    "233-WAM" => "WeightedAverageMaturity",
    "233-WHOLE" => "WholePool",
    "233-YIELD" => "YieldRange",
    "235-AFTERTAX" => "AfterTaxYield",
    "235-ANNUAL" => "AnnualYield",
    "235-ATISSUE" => "YieldAtIssue",
    "235-AVGMATURITY" => "YieldToAverageMaturity",
    "235-BOOK" => "BookYield",
    "235-CALL" => "YieldToNextCall",
    "235-CHANGE" => "YieldChangeSinceClose",
    "235-CLOSE" => "ClosingYield",
    "235-COMPOUND" => "CompoundYield",
    "235-CURRENT" => "CurrentYield",
    "235-GROSS" => "TrueGrossYield",
    "235-GOVTEQUIV" => "GvntEquivalentYield",
    "235-INFLATION" => "YieldWithInflationAssumption",
    "235-INVERSEFLOATER" => "InverseFloaterBondYield",
    "235-LASTCLOSE" => "MostRecentClosingYield",
    "235-LASTMONTH" => "ClosingYieldMostRecentMonth",
    "235-LASTQUARTER" => "ClosingYieldMostRecentQuarter",
    "235-LASTYEAR" => "ClosingYieldMostRecentYear",
    "235-LONGAVGLIFE" => "YieldToLongestAverageLife",
    "235-MARK" => "MarkToMarketYield",
    "235-MATURITY" => "YieldToMaturity",
    "235-NEXTREFUND" => "YieldToNextRefund",
    "235-OPENAVG" => "OpenAverageYield",
    "235-PUT" => "YieldToNextPut",
    "235-PREVCLOSE" => "PreviousCloseYield",
    "235-PROCEEDS" => "ProceedsYield",
    "235-SEMIANNUAL" => "SemiAnnualYield",
    "235-SHORTAVGLIFE" => "YieldToShortestAverageLife",
    "235-SIMPLE" => "SimpleYield",
    "235-TAXEQUIV" => "TaxEquivalentYield",
    "235-TENDER" => "YieldToTenderDate",
    "235-TRUE" => "TrueYield",
    "235-VALUE1/32" => "YieldValueOf132",
    "235-WORST" => "YieldToWorst",
    "258-Y" => "Yes",
    "258-N" => "No",
    "263-0" => "Snapshot",
    "263-1" => "SnapshotAndUpdates",
    "263-2" => "DisablePreviousSnapshot",
    "265-0" => "FullRefresh",
    "265-1" => "IncrementalRefresh",
    "266-Y" => "Yes",
    "266-N" => "No",
    "269-0" => "Bid",
    "269-1" => "Offer",
    "269-2" => "Trade",
    "269-3" => "IndexValue",
    "269-4" => "OpeningPrice",
    "269-5" => "ClosingPrice",
    "269-6" => "SettlementPrice",
    "269-7" => "TradingSessionHighPrice",
    "269-8" => "TradingSessionLowPrice",
    "269-9" => "TradingSessionVwapPrice",
    "269-A" => "Imbalance",
    "269-B" => "TradeVolume",
    "269-C" => "OpenInterest",
    "274-0" => "PlusTick",
    "274-1" => "ZeroPlusTick",
    "274-2" => "MinusTick",
    "274-3" => "ZeroMinusTick",
    "276-A" => "Open",
    "276-B" => "Closed",
    "276-C" => "ExchangeBest",
    "276-D" => "ConsolidatedBest",
    "276-E" => "Locked",
    "276-F" => "Crossed",
    "276-G" => "Depth",
    "276-H" => "FastTrading",
    "276-I" => "NonFirm",
    "277-A" => "Cash",
    "277-B" => "AveragePriceTrade",
    "277-C" => "CashTrade",
    "277-D" => "NextDay",
    "277-E" => "Opening",
    "277-F" => "IntradayTradeDetail",
    "277-G" => "Rule127Trade",
    "277-H" => "Rule155Trade",
    "277-I" => "SoldLast",
    "277-J" => "NextDayTrade",
    "277-K" => "Opened",
    "277-L" => "Seller",
    "277-M" => "Sold",
    "277-N" => "StoppedStock",
    "277-P" => "ImbalanceMoreBuyers",
    "277-Q" => "ImbalanceMoreSellers",
    "277-R" => "OpeningPrice",
    "279-0" => "New",
    "279-1" => "Change",
    "279-2" => "Delete",
    "281-0" => "UnknownSymbol",
    "281-1" => "DuplicateMdReqId",
    "281-2" => "InsufficientBandwidth",
    "281-3" => "InsufficientPermissions",
    "281-4" => "UnsupportedSubscriptionRequestType",
    "281-5" => "UnsupportedMarketDepth",
    "281-6" => "UnsupportedMdUpdateType",
    "281-7" => "UnsupportedAggregatedBook",
    "281-8" => "UnsupportedMdEntryType",
    "281-9" => "UnsupportedTradingSessionId",
    "281-A" => "UnsupportedScope",
    "281-B" => "UnsupportedOpenCloseSettleFlag",
    "281-C" => "UnsupportedMdImplicitDelete",
    "285-0" => "Cancellation",
    "285-1" => "Error",
    "286-0" => "DailyOpen",
    "286-1" => "SessionOpen",
    "286-2" => "DeliverySettlementEntry",
    "286-3" => "ExpectedEntry",
    "286-4" => "EntryFromPreviousBusinessDay",
    "286-5" => "TheoreticalPriceValue",
    "291-1" => "Bankrupt",
    "291-2" => "PendingDelisting",
    "292-A" => "ExDividend",
    "292-B" => "ExDistribution",
    "292-C" => "ExRights",
    "292-D" => "New",
    "292-E" => "ExInterest",
    "297-0" => "Accepted",
    "297-1" => "CancelForSymbol",
    "297-2" => "CanceledForSecurityType",
    "297-3" => "CanceledForUnderlying",
    "297-4" => "CanceledAll",
    "297-5" => "Rejected",
    "297-6" => "RemovedFromMarket",
    "297-7" => "Expired",
    "297-8" => "Query",
    "297-9" => "QuoteNotFound",
    "297-10" => "Pending",
    "297-11" => "Pass",
    "297-12" => "LockedMarketWarning",
    "297-13" => "CrossMarketWarning",
    "297-14" => "CanceledDueToLockMarket",
    "297-15" => "CanceledDueToCrossMarket",
    "298-1" => "CancelForOneOrMoreSecurities",
    "298-2" => "CancelForSecurityType",
    "298-3" => "CancelForUnderlyingSecurity",
    "298-4" => "CancelAllQuotes",
    "300-1" => "UnknownSymbol",
    "300-2" => "Exchange",
    "300-3" => "QuoteRequestExceedsLimit",
    "300-4" => "TooLateToEnter",
    "300-5" => "UnknownQuote",
    "300-6" => "DuplicateQuote",
    "300-7" => "InvalidBid",
    "300-8" => "InvalidPrice",
    "300-9" => "NotAuthorizedToQuoteSecurity",
    "300-99" => "Other",
    "301-0" => "NoAcknowledgement",
    "301-1" => "AcknowledgeOnlyNegativeOrErroneousQuotes",
    "301-2" => "AcknowledgeEachQuoteMessage",
    "303-1" => "Manual",
    "303-2" => "Automatic",
    "321-0" => "RequestSecurityIdentityAndSpecifications",
    "321-1" => "RequestSecurityIdentityForSpecifications",
    "321-2" => "RequestListSecurityTypes",
    "321-3" => "RequestListSecurities",
    "323-1" => "AcceptAsIs",
    "323-2" => "AcceptWithRevisions",
    "323-5" => "RejectSecurityProposal",
    "323-6" => "CannotMatchSelectionCriteria",
    "325-Y" => "Yes",
    "325-N" => "No",
    "326-1" => "OpeningDelay",
    "326-2" => "TradingHalt",
    "326-3" => "Resume",
    "326-4" => "NoOpen",
    "326-5" => "PriceIndication",
    "326-6" => "TradingRangeIndication",
    "326-7" => "MarketImbalanceBuy",
    "326-8" => "MarketImbalanceSell",
    "326-9" => "MarketOnCloseImbalanceBuy",
    "326-10" => "MarketOnCloseImbalanceSell",
    "326-12" => "NoMarketImbalance",
    "326-13" => "NoMarketOnCloseImbalance",
    "326-14" => "ItsPreOpening",
    "326-15" => "NewPriceIndication",
    "326-16" => "TradeDisseminationTime",
    "326-17" => "ReadyToTrade",
    "326-18" => "NotAvailableForTrading",
    "326-19" => "NotTradedOnThisMarket",
    "326-20" => "UnknownOrInvalid",
    "326-21" => "PreOpen",
    "326-22" => "OpeningRotation",
    "326-23" => "FastMarket",
    "327-I" => "OrderImbalance",
    "327-X" => "EquipmentChangeover",
    "327-P" => "NewsPending",
    "327-D" => "NewsDissemination",
    "327-E" => "OrderInflux",
    "327-M" => "AdditionalInformation",
    "328-Y" => "Yes",
    "328-N" => "No",
    "329-Y" => "Yes",
    "329-N" => "No",
    "334-1" => "Cancel",
    "334-2" => "Error",
    "334-3" => "Correction",
    "338-1" => "Electronic",
    "338-2" => "OpenOutcry",
    "338-3" => "TwoParty",
    "339-1" => "Testing",
    "339-2" => "Simulated",
    "339-3" => "Production",
    "340-0" => "Unknown",
    "340-1" => "Halted",
    "340-2" => "Open",
    "340-3" => "Closed",
    "340-4" => "PreOpen",
    "340-5" => "PreClose",
    "340-6" => "RequestRejected",
    "347-ISO-2022-JP" => "Iso2022Jp",
    "347-EUC-JP" => "Eucjp",
    "347-ShiftJIS" => "ShiftJis",
    "347-UTF-8" => "Utf8",
    "373-0" => "InvalidTagNumber",
    "373-1" => "RequiredTagMissing",
    "373-2" => "TagNotDefinedForThisMessageType",
    "373-3" => "UndefinedTag",
    "373-4" => "TagSpecifiedWithoutAValue",
    "373-5" => "ValueIsIncorrect",
    "373-6" => "IncorrectDataFormatForValue",
    "373-7" => "DecryptionProblem",
    "373-8" => "SignatureProblem",
    "373-9" => "CompIdProblem",
    "373-10" => "SendingTimeAccuracyProblem",
    "373-11" => "InvalidMsgType",
    "373-12" => "XmlValidationError",
    "373-13" => "TagAppearsMoreThanOnce",
    "373-14" => "TagSpecifiedOutOfRequiredOrder",
    "373-15" => "RepeatingGroupFieldsOutOfOrder",
    "373-16" => "IncorrectNumInGroupCountForRepeatingGroup",
    "373-17" => "Non",
    "373-99" => "Other",
    "374-N" => "New",
    "374-C" => "Cancel",
    "377-Y" => "Yes",
    "377-N" => "No",
    "378-0" => "GtCorporateAction",
    "378-1" => "GtRenewal",
    "378-2" => "VerbalChange",
    "378-3" => "RepricingOfOrder",
    "378-4" => "BrokerOption",
    "378-5" => "PartialDeclineOfOrderQty",
    "378-6" => "CancelOnTradingHalt",
    "378-7" => "CancelOnSystemFailure",
    "378-8" => "Market",
    "378-9" => "Canceled",
    "378-10" => "WarehouseRecap",
    "378-99" => "Other",
    "380-0" => "Other",
    "380-1" => "UnknownId",
    "380-2" => "UnknownSecurity",
    "380-3" => "UnsupportedMessageType",
    "380-4" => "ApplicationNotAvailable",
    "380-5" => "ConditionallyRequiredFieldMissing",
    "380-6" => "NotAuthorized",
    "380-7" => "DeliverToFirmNotAvailableAtThisTime",
    "385-S" => "Send",
    "385-R" => "Receive",
    "388-0" => "RelatedToDisplayedPrice",
    "388-1" => "RelatedToMarketPrice",
    "388-2" => "RelatedToPrimaryPrice",
    "388-3" => "RelatedToLocalPrimaryPrice",
    "388-4" => "RelatedToMidpointPrice",
    "388-5" => "RelatedToLastTradePrice",
    "388-6" => "RelatedToVwap",
    "394-1" => "NonDisclosed",
    "394-2" => "Disclosed",
    "394-3" => "NoBiddingProcess",
    "399-1" => "Sector",
    "399-2" => "Country",
    "399-3" => "Index",
    "401-1" => "SideValue1",
    "401-2" => "SideValue2",
    "409-1" => "FiveDayMovingAverage",
    "409-2" => "TwentyDayMovingAverage",
    "409-3" => "NormalMarketSize",
    "409-4" => "Other",
    "411-Y" => "Yes",
    "411-N" => "No",
    "414-1" => "BuySideRequests",
    "414-2" => "SellSideSends",
    "414-3" => "RealTimeExecutionReports",
    "416-1" => "Net",
    "416-2" => "Gross",
    "418-R" => "RiskTrade",
    "418-G" => "VwapGuarantee",
    "418-A" => "Agency",
    "418-J" => "GuaranteedClose",
    "419-2" => "ClosingPriceAtMorningSession",
    "419-3" => "ClosingPrice",
    "419-4" => "CurrentPrice",
    "419-5" => "Sq",
    "419-6" => "VwapThroughADay",
    "419-7" => "VwapThroughAMorningSession",
    "419-8" => "VwapThroughAnAfternoonSession",
    "419-9" => "VwapThroughADayExcept",
    "419-A" => "VwapThroughAMorningSessionExcept",
    "419-B" => "VwapThroughAnAfternoonSessionExcept",
    "419-C" => "Strike",
    "419-D" => "Open",
    "419-Z" => "Others",
    "423-1" => "Percentage",
    "423-2" => "PerUnit",
    "423-3" => "FixedAmount",
    "423-4" => "Discount",
    "423-5" => "Premium",
    "423-6" => "Spread",
    "423-7" => "TedPrice",
    "423-8" => "TedYield",
    "423-9" => "Yield",
    "423-10" => "FixedCabinetTradePrice",
    "423-11" => "VariableCabinetTradePrice",
    "427-0" => "BookOutAllTradesOnDayOfExecution",
    "427-1" => "AccumulateUntilFilledOrExpired",
    "427-2" => "AccumulateUntilVerballlyNotifiedOtherwise",
    "429-1" => "Ack",
    "429-2" => "Response",
    "429-3" => "Timed",
    "429-4" => "ExecStarted",
    "429-5" => "AllDone",
    "429-6" => "Alert",
    "430-1" => "Net",
    "430-2" => "Gross",
    "431-1" => "InBiddingProcess",
    "431-2" => "ReceivedForExecution",
    "431-3" => "Executing",
    "431-4" => "Cancelling",
    "431-5" => "Alert",
    "431-6" => "AllDone",
    "431-7" => "Reject",
    "433-1" => "Immediate",
    "433-2" => "WaitForInstruction",
    "433-3" => "SellDriven",
    "433-4" => "BuyDrivenCashTopUp",
    "433-5" => "BuyDrivenCashWithdraw",
    "434-1" => "OrderCancelRequest",
    "434-2" => "OrderCancel",
    "442-1" => "SingleSecurity",
    "442-2" => "IndividualLegOfAMultiLegSecurity",
    "442-3" => "MultiLegSecurity",
    "447-B" => "Bic",
    "447-C" => "GeneralIdentifier",
    "447-D" => "Proprietary",
    "447-E" => "IsoCountryCode",
    "447-F" => "SettlementEntityLocation",
    "447-G" => "Mic",
    "447-H" => "CsdParticipant",
    "447-1" => "KoreanInvestorId",
    "447-2" => "TaiwaneseForeignInvestorId",
    "447-3" => "TaiwaneseTradingAcct",
    "447-4" => "MalaysianCentralDepository",
    "447-5" => "ChineseInvestorId",
    "447-6" => "UkNationalInsuranceOrPensionNumber",
    "447-7" => "UsSocialSecurityNumber",
    "447-8" => "UsEmployerOrTaxIdNumber",
    "447-9" => "AustralianBusinessNumber",
    "447-A" => "AustralianTaxFileNumber",
    "447-I" => "IsitcAcronym",
    "452-1" => "ExecutingFirm",
    "452-2" => "BrokerOfCredit",
    "452-3" => "ClientId",
    "452-4" => "ClearingFirm",
    "452-5" => "InvestorId",
    "452-6" => "IntroducingFirm",
    "452-7" => "EnteringFirm",
    "452-8" => "Locate",
    "452-9" => "FundManagerClientId",
    "452-10" => "SettlementLocation",
    "452-11" => "OrderOriginationTrader",
    "452-12" => "ExecutingTrader",
    "452-13" => "OrderOriginationFirm",
    "452-14" => "GiveupClearingFirm",
    "452-15" => "CorrespondantClearingFirm",
    "452-16" => "ExecutingSystem",
    "452-17" => "ContraFirm",
    "452-18" => "ContraClearingFirm",
    "452-19" => "SponsoringFirm",
    "452-20" => "UnderlyingContraFirm",
    "452-21" => "ClearingOrganization",
    "452-22" => "Exchange",
    "452-24" => "CustomerAccount",
    "452-25" => "CorrespondentClearingOrganization",
    "452-26" => "CorrespondentBroker",
    "452-27" => "Buyer",
    "452-28" => "Custodian",
    "452-29" => "Intermediary",
    "452-30" => "Agent",
    "452-31" => "SubCustodian",
    "452-32" => "Beneficiary",
    "452-33" => "InterestedParty",
    "452-34" => "RegulatoryBody",
    "452-35" => "LiquidityProvider",
    "452-36" => "EnteringTrader",
    "452-37" => "ContraTrader",
    "452-38" => "PositionAccount",
    "460-1" => "Agency",
    "460-2" => "Commodity",
    "460-3" => "Corporate",
    "460-4" => "Currency",
    "460-5" => "Equity",
    "460-6" => "Government",
    "460-7" => "Index",
    "460-8" => "Loan",
    "460-9" => "Moneymarket",
    "460-10" => "Mortgage",
    "460-11" => "Municipal",
    "460-12" => "Other",
    "460-13" => "Financing",
    "464-Y" => "Yes",
    "464-N" => "No",
    "468-0" => "RoundToNearest",
    "468-1" => "RoundDown",
    "468-2" => "RoundUp",
    "477-1" => "Crest",
    "477-2" => "Nscc",
    "477-3" => "Euroclear",
    "477-4" => "Clearstream",
    "477-5" => "Cheque",
    "477-6" => "TelegraphicTransfer",
    "477-7" => "FedWire",
    "477-8" => "DirectCredit",
    "477-9" => "AchCredit",
    "477-10" => "Bpay",
    "477-11" => "HighValueClearingSystemHvacs",
    "477-12" => "ReinvestInFund",
    "480-Y" => "Yes",
    "480-N" => "NoExecutionOnly",
    "480-M" => "NoWaiverAgreement",
    "480-O" => "NoInstitutional",
    "481-Y" => "Passed",
    "481-N" => "NotChecked",
    "481-1" => "ExemptBelowLimit",
    "481-2" => "ExemptMoneyType",
    "481-3" => "ExemptAuthorised",
    "484-B" => "BidPrice",
    "484-C" => "CreationPrice",
    "484-D" => "CreationPricePlusAdjustmentPercent",
    "484-E" => "CreationPricePlusAdjustmentAmount",
    "484-O" => "OfferPrice",
    "484-P" => "OfferPriceMinusAdjustmentPercent",
    "484-Q" => "OfferPriceMinusAdjustmentAmount",
    "484-S" => "SinglePrice",
    "492-1" => "Crest",
    "492-2" => "Nscc",
    "492-3" => "Euroclear",
    "492-4" => "Clearstream",
    "492-5" => "Cheque",
    "492-6" => "TelegraphicTransfer",
    "492-7" => "FedWire",
    "492-8" => "DebitCard",
    "492-9" => "DirectDebit",
    "492-10" => "DirectCredit",
    "492-11" => "CreditCard",
    "492-12" => "AchDebit",
    "492-13" => "AchCredit",
    "492-14" => "Bpay",
    "492-15" => "HighValueClearingSystem",
    "495-0" => "None",
    "495-1" => "MaxiIsa",
    "495-2" => "Tessa",
    "495-3" => "MiniCashIsa",
    "495-4" => "MiniStocksAndSharesIsa",
    "495-5" => "MiniInsuranceIsa",
    "495-6" => "CurrentYearPayment",
    "495-7" => "PriorYearPayment",
    "495-8" => "AssetTransfer",
    "495-9" => "EmployeePriorYear",
    "495-10" => "EmployeeCurrentYear",
    "495-11" => "EmployerPriorYear",
    "495-12" => "EmployerCurrentYear",
    "495-13" => "NonFundPrototypeIra",
    "495-14" => "NonFundQualifiedPlan",
    "495-15" => "DefinedContributionPlan",
    "495-16" => "Ira",
    "495-17" => "IraRollover",
    "495-18" => "Keogh",
    "495-19" => "ProfitSharingPlan",
    "495-20" => "Us401K",
    "495-21" => "SelfDirectedIra",
    "495-22" => "Us403b",
    "495-23" => "Us457",
    "495-24" => "RothIraPrototype",
    "495-25" => "RothIraNonPrototype",
    "495-26" => "RothConversionIraPrototype",
    "495-27" => "RothConversionIraNonPrototype",
    "495-28" => "EducationIraPrototype",
    "495-29" => "EducationIraNonPrototype",
    "497-Y" => "Yes",
    "497-N" => "No",
    "506-A" => "Accepted",
    "506-R" => "Rejected",
    "506-H" => "Held",
    "506-N" => "Reminder",
    "507-1" => "InvalidAccountType",
    "507-2" => "InvalidTaxExemptType",
    "507-3" => "InvalidOwnershipType",
    "507-4" => "NoRegDetails",
    "507-5" => "InvalidRegSeqNo",
    "507-6" => "InvalidRegDetails",
    "507-7" => "InvalidMailingDetails",
    "507-8" => "InvalidMailingInstructions",
    "507-9" => "InvalidInvestorId",
    "507-10" => "InvalidInvestorIdSource",
    "507-11" => "InvalidDateOfBirth",
    "507-12" => "InvalidCountry",
    "507-13" => "InvalidDistribInstns",
    "507-14" => "InvalidPercentage",
    "507-15" => "InvalidPaymentMethod",
    "507-16" => "InvalidAccountName",
    "507-17" => "InvalidAgentCode",
    "507-18" => "InvalidAccountNum",
    "507-99" => "Other",
    "514-0" => "New",
    "514-1" => "Replace",
    "514-2" => "Cancel",
    "517-J" => "JointInvestors",
    "517-T" => "TenantsInCommon",
    "517-2" => "JointTrustees",
    "519-1" => "CommissionAmount",
    "519-2" => "CommissionPercent",
    "519-3" => "InitialChargeAmount",
    "519-4" => "InitialChargePercent",
    "519-5" => "DiscountAmount",
    "519-6" => "DiscountPercent",
    "519-7" => "DilutionLevyAmount",
    "519-8" => "DilutionLevyPercent",
    "519-9" => "ExitChargeAmount",
    "519-10" => "ExitChargePercent",
    "519-11" => "FundBasedRenewalCommissionPercent",
    "519-12" => "ProjectedFundValue",
    "519-13" => "FundBasedRenewalCommissionOnOrder",
    "519-14" => "FundBasedRenewalCommissionOnFund",
    "519-15" => "NetSettlementAmount",
    "522-1" => "IndividualInvestor",
    "522-2" => "PublicCompany",
    "522-3" => "PrivateCompany",
    "522-4" => "IndividualTrustee",
    "522-5" => "CompanyTrustee",
    "522-6" => "PensionPlan",
    "522-7" => "CustodianUnderGiftsToMinorsAct",
    "522-8" => "Trusts",
    "522-9" => "Fiduciaries",
    "522-10" => "NetworkingSubAccount",
    "522-11" => "NonProfitOrganization",
    "522-12" => "CorporateBody",
    "522-13" => "Nominee",
    "528-A" => "Agency",
    "528-G" => "Proprietary",
    "528-I" => "Individual",
    "528-P" => "Principal",
    "528-R" => "RisklessPrincipal",
    "528-W" => "AgentForOtherMember",
    "529-1" => "ProgramTrade",
    "529-2" => "IndexArbitrage",
    "529-3" => "NonIndexArbitrage",
    "529-4" => "CompetingMarketMaker",
    "529-5" => "ActingAsMarketMakerOrSpecialistInSecurity",
    "529-6" => "ActingAsMarketMakerOrSpecialistInUnderlying",
    "529-7" => "ForeignEntity",
    "529-8" => "ExternalMarketParticipant",
    "529-9" => "ExternalInterConnectedMarketLinkage",
    "529-A" => "RisklessArbitrage",
    "530-1" => "CancelOrdersForASecurity",
    "530-2" => "CancelOrdersForAnUnderlyingSecurity",
    "530-3" => "CancelOrdersForAProduct",
    "530-4" => "CancelOrdersForAcfiCode",
    "530-5" => "CancelOrdersForASecurityType",
    "530-6" => "CancelOrdersForATradingSession",
    "530-7" => "CancelAllOrders",
    "531-0" => "CancelRequestRejected",
    "531-1" => "CancelOrdersForASecurity",
    "531-2" => "CancelOrdersForAnUnderlyingSecurity",
    "531-3" => "CancelOrdersForAProduct",
    "531-4" => "CancelOrdersForAcfiCode",
    "531-5" => "CancelOrdersForASecurityType",
    "531-6" => "CancelOrdersForATradingSession",
    "531-7" => "CancelAllOrders",
    "532-0" => "MassCancelNotSupported",
    "532-1" => "InvalidOrUnknownSecurity",
    "532-2" => "InvalidOrUnkownUnderlyingSecurity",
    "532-3" => "InvalidOrUnknownProduct",
    "532-4" => "InvalidOrUnknownCfiCode",
    "532-5" => "InvalidOrUnknownSecurityType",
    "532-6" => "InvalidOrUnknownTradingSession",
    "532-99" => "Other",
    "537-0" => "Indicative",
    "537-1" => "Tradeable",
    "537-2" => "RestrictedTradeable",
    "537-3" => "Counter",
    "544-1" => "Cash",
    "544-2" => "MarginOpen",
    "544-3" => "MarginClose",
    "546-1" => "LocalMarket",
    "546-2" => "National",
    "546-3" => "Global",
    "547-Y" => "Yes",
    "547-N" => "No",
    "549-1" => "CrossAon",
    "549-2" => "CrossIoc",
    "549-3" => "CrossOneSide",
    "549-4" => "CrossSamePrice",
    "550-0" => "None",
    "550-1" => "BuySideIsPrioritized",
    "550-2" => "SellSideIsPrioritized",
    "552-1" => "OneSide",
    "552-2" => "BothSides",
    "559-0" => "Symbol",
    "559-1" => "SecurityTypeAnd",
    "559-2" => "Product",
    "559-3" => "TradingSessionId",
    "559-4" => "AllSecurities",
    "560-0" => "ValidRequest",
    "560-1" => "InvalidOrUnsupportedRequest",
    "560-2" => "NoInstrumentsFound",
    "560-3" => "NotAuthorizedToRetrieveInstrumentData",
    "560-4" => "InstrumentDataTemporarilyUnavailable",
    "560-5" => "RequestForInstrumentDataNotSupported",
    "563-0" => "ReportByMulitlegSecurityOnly",
    "563-1" => "ReportByMultilegSecurityAndInstrumentLegs",
    "563-2" => "ReportByInstrumentLegsOnly",
    "567-1" => "UnknownOrInvalidTradingSessionId",
    "567-99" => "Other",
    "569-0" => "AllTrades",
    "569-1" => "MatchedTradesMatchingCriteria",
    "569-2" => "UnmatchedTradesThatMatchCriteria",
    "569-3" => "UnreportedTradesThatMatchCriteria",
    "569-4" => "AdvisoriesThatMatchCriteria",
    "570-Y" => "Yes",
    "570-N" => "No",
    "573-0" => "Compared",
    "573-1" => "Uncompared",
    "573-2" => "AdvisoryOrAlert",
    "574-A1" => "ExactMatchPlus4BadgesExecTime",
    "574-A2" => "ExactMatchPlus4Badges",
    "574-A3" => "ExactMatchPlus2BadgesExecTime",
    "574-A4" => "ExactMatchPlus2Badges",
    "574-A5" => "ExactMatchPlusExecTime",
    "574-AQ" => "StampedAdvisoriesOrSpecialistAccepts",
    "574-S1" => "A1ExactMatchSummarizedQuantity",
    "574-S2" => "A2ExactMatchSummarizedQuantity",
    "574-S3" => "A3ExactMatchSummarizedQuantity",
    "574-S4" => "A4ExactMatchSummarizedQuantity",
    "574-S5" => "A5ExactMatchSummarizedQuantity",
    "574-M1" => "ExactMatchMinusBadgesTimes",
    "574-M2" => "SummarizedMatchMinusBadgesTimes",
    "574-MT" => "OcsLockedIn",
    "574-M3" => "ActAcceptedTrade",
    "574-M4" => "ActDefaultTrade",
    "574-M5" => "ActDefaultAfterM2",
    "574-M6" => "Actm6Match",
    "575-Y" => "Yes",
    "575-N" => "No",
    "577-0" => "ProcessNormally",
    "577-1" => "ExcludeFromAllNetting",
    "577-2" => "BilateralNettingOnly",
    "577-3" => "ExClearing",
    "577-4" => "SpecialTrade",
    "577-5" => "MultilateralNetting",
    "577-6" => "ClearAgainstCentralCounterparty",
    "577-7" => "ExcludeFromCentralCounterparty",
    "577-8" => "ManualMode",
    "577-9" => "AutomaticPostingMode",
    "577-10" => "AutomaticGiveUpMode",
    "577-11" => "QualifiedServiceRepresentativeQsr",
    "577-12" => "CustomerTrade",
    "577-13" => "SelfClearing",
    "581-1" => "CarriedCustomerSide",
    "581-2" => "CarriedNonCustomerSide",
    "581-3" => "HouseTrader",
    "581-4" => "FloorTrader",
    "581-6" => "CarriedNonCustomerSideCrossMargined",
    "581-7" => "HouseTraderCrossMargined",
    "581-8" => "JointBackOfficeAccount",
    "582-1" => "MemberTradingForTheirOwnAccount",
    "582-2" => "ClearingFirmTradingForItsProprietaryAccount",
    "582-3" => "MemberTradingForAnotherMember",
    "582-4" => "AllOther",
    "585-1" => "StatusForOrdersForASecurity",
    "585-2" => "StatusForOrdersForAnUnderlyingSecurity",
    "585-3" => "StatusForOrdersForAProduct",
    "585-4" => "StatusForOrdersForAcfiCode",
    "585-5" => "StatusForOrdersForASecurityType",
    "585-6" => "StatusForOrdersForATradingSession",
    "585-7" => "StatusForAllOrders",
    "585-8" => "StatusForOrdersForAPartyId",
    "589-0" => "Auto",
    "589-1" => "SpeakWithOrderInitiatorBeforeBooking",
    "589-2" => "Accumulate",
    "590-0" => "EachPartialExecutionIsABookableUnit",
    "590-1" => "AggregatePartialExecutionsOnThisOrder",
    "590-2" => "AggregateExecutionsForThisSymbol",
    "591-0" => "ProRata",
    "591-1" => "DoNotProRata",
    "626-1" => "Calculated",
    "626-2" => "Preliminary",
    "626-5" => "ReadyToBook",
    "626-7" => "WarehouseInstruction",
    "626-8" => "RequestToIntermediary",
    "635-B" => "CboeMember",
    "635-C" => "NonMemberAndCustomer",
    "635-E" => "EquityMemberAndClearingMember",
    "635-F" => "FullAndAssociateMember",
    "635-H" => "Firms106HAnd106J",
    "635-I" => "Gim",
    "635-L" => "Lessee106FEmployees",
    "635-M" => "AllOtherOwnershipTypes",
    "635-1" => "FirstYearDelegate",
    "635-2" => "SecondYearDelegate",
    "635-3" => "ThirdYearDelegate",
    "635-4" => "FourthYearDelegate",
    "635-5" => "FifthYearDelegate",
    "635-9" => "SixthYearDelegate",
    "636-Y" => "Yes",
    "636-N" => "No",
    "638-0" => "PriorityUnchanged",
    "638-1" => "LostPriorityAsResultOfOrderChange",
    "650-Y" => "Yes",
    "650-N" => "No",
    "658-1" => "UnknownSymbol",
    "658-2" => "Exchange",
    "658-3" => "QuoteRequestExceedsLimit",
    "658-4" => "TooLateToEnter",
    "658-5" => "InvalidPrice",
    "658-6" => "NotAuthorizedToRequestQuote",
    "658-7" => "NoMatchForInquiry",
    "658-8" => "NoMarketForInstrument",
    "658-9" => "NoInventory",
    "658-10" => "Pass",
    "658-99" => "Other",
    "660-1" => "Bic",
    "660-2" => "SidCode",
    "660-3" => "Tfm",
    "660-4" => "Omgeo",
    "660-5" => "DtccCode",
    "660-99" => "Other",
    "665-1" => "Received",
    "665-2" => "MismatchedAccount",
    "665-3" => "MissingSettlementInstructions",
    "665-4" => "Confirmed",
    "665-5" => "RequestRejected",
    "666-0" => "New",
    "666-1" => "Replace",
    "666-2" => "Cancel",
    "668-1" => "BookEntry",
    "668-2" => "Bearer",
    "690-1" => "ParForPar",
    "690-2" => "ModifiedDuration",
    "690-4" => "Risk",
    "690-5" => "Proceeds",
    "692-1" => "Percent",
    "692-2" => "PerShare",
    "692-3" => "FixedAmount",
    "692-4" => "Discount",
    "692-5" => "Premium",
    "692-6" => "Spread",
    "692-7" => "TedPrice",
    "692-8" => "TedYield",
    "692-9" => "YieldSpread",
    "692-10" => "Yield",
    "694-1" => "Hit",
    "694-2" => "Counter",
    "694-3" => "Expired",
    "694-4" => "Cover",
    "694-5" => "DoneAway",
    "694-6" => "Pass",
    "703-TQ" => "TransactionQuantity",
    "703-IAS" => "IntraSpreadQty",
    "703-IES" => "InterSpreadQty",
    "703-FIN" => "EndOfDayQty",
    "703-SOD" => "StartOfDayQty",
    "703-EX" => "OptionExerciseQty",
    "703-AS" => "OptionAssignment",
    "703-TX" => "TransactionFromExercise",
    "703-TA" => "TransactionFromAssignment",
    "703-PIT" => "PitTradeQty",
    "703-TRF" => "TransferTradeQty",
    "703-ETR" => "ElectronicTradeQty",
    "703-ALC" => "AllocationTradeQty",
    "703-PA" => "AdjustmentQty",
    "703-ASF" => "AsOfTradeQty",
    "703-DLV" => "DeliveryQty",
    "703-TOT" => "TotalTransactionQty",
    "703-XM" => "CrossMarginQty",
    "703-SPL" => "IntegralSplit",
    "706-0" => "Submitted",
    "706-1" => "Accepted",
    "706-2" => "Rejected",
    "707-FMTM" => "FinalMarkToMarketAmount",
    "707-IMTM" => "IncrementalMarkToMarketAmount",
    "707-TVAR" => "TradeVariationAmount",
    "707-SMTM" => "StartOfDayMarkToMarketAmount",
    "707-PREM" => "PremiumAmount",
    "707-CRES" => "CashResidualAmount",
    "707-CASH" => "CashAmount",
    "707-VADJ" => "ValueAdjustedAmount",
    "709-1" => "Exercise",
    "709-2" => "DoNotExercise",
    "709-3" => "PositionAdjustment",
    "709-4" => "PositionChangeSubmission",
    "709-5" => "Pledge",
    "712-1" => "New",
    "712-2" => "Replace",
    "712-3" => "Cancel",
    "716-ITD" => "Intraday",
    "716-RTH" => "RegularTradingHours",
    "716-ETH" => "ElectronicTradingHours",
    "718-0" => "ProcessRequestAsMarginDisposition",
    "718-1" => "DeltaPlus",
    "718-2" => "DeltaMinus",
    "718-3" => "Final",
    "722-0" => "Accepted",
    "722-1" => "AcceptedWithWarnings",
    "722-2" => "Rejected",
    "722-3" => "Completed",
    "722-4" => "CompletedWithWarnings",
    "723-0" => "SuccessfulCompletion",
    "723-1" => "Rejected",
    "723-99" => "Other",
    "724-0" => "Positions",
    "724-1" => "Trades",
    "724-2" => "Exercises",
    "724-3" => "Assignments",
    "725-0" => "Inband",
    "725-1" => "OutOfBand",
    "728-0" => "ValidRequest",
    "728-1" => "InvalidOrUnsupportedRequest",
    "728-2" => "NoPositionsFoundThatMatchCriteria",
    "728-3" => "NotAuthorizedToRequestPositions",
    "728-4" => "RequestForPositionNotSupported",
    "728-99" => "Other",
    "729-0" => "Completed",
    "729-1" => "CompletedWithWarnings",
    "729-2" => "Rejected",
    "731-1" => "Final",
    "731-2" => "Theoretical",
    "744-R" => "Random",
    "744-P" => "ProRata",
    "747-A" => "Automatic",
    "747-M" => "Manual",
    "749-0" => "Successful",
    "749-1" => "InvalidOrUnknownInstrument",
    "749-2" => "InvalidTypeOfTradeRequested",
    "749-3" => "InvalidParties",
    "749-4" => "InvalidTransportTypeRequested",
    "749-5" => "InvalidDestinationRequested",
    "749-8" => "TradeRequestTypeNotSupported",
    "749-9" => "NotAuthorized",
    "749-99" => "Other",
    "750-0" => "Accepted",
    "750-1" => "Completed",
    "750-2" => "Rejected",
    "751-0" => "Successful",
    "751-1" => "InvalidPartyOnformation",
    "751-2" => "UnknownInstrument",
    "751-3" => "UnauthorizedToReportTrades",
    "751-4" => "InvalidTradeType",
    "751-99" => "Other",
    "752-1" => "SingleSecurity",
    "752-2" => "IndividualLegOfAMultilegSecurity",
    "752-3" => "MultilegSecurity",
    "770-1" => "ExecutionTime",
    "770-2" => "TimeIn",
    "770-3" => "TimeOut",
    "770-4" => "BrokerReceipt",
    "770-5" => "BrokerExecution",
    "773-1" => "Status",
    "773-2" => "Confirmation",
    "773-3" => "ConfirmationRequestRejected",
    "774-1" => "MismatchedAccount",
    "774-2" => "MissingSettlementInstructions",
    "774-99" => "Other",
    "775-0" => "RegularBooking",
    "775-1" => "Cfd",
    "775-2" => "TotalReturnSwap",
    "780-0" => "UseDefaultInstructions",
    "780-1" => "DeriveFromParametersProvided",
    "780-2" => "FullDetailsProvided",
    "780-3" => "SsidbiDsProvided",
    "780-4" => "PhoneForInstructions",
    "787-S" => "Securities",
    "787-C" => "Cash",
    "788-1" => "Overnight",
    "788-2" => "Term",
    "788-3" => "Flexible",
    "788-4" => "Open",
    "792-0" => "UnableToProcessRequest",
    "792-1" => "UnknownAccount",
    "792-2" => "NoMatchingSettlementInstructionsFound",
    "792-99" => "Other",
    "794-3" => "SellsideCalculatedUsingPreliminary",
    "794-4" => "SellsideCalculatedWithoutPreliminary",
    "794-5" => "WarehouseRecap",
    "794-8" => "RequestToIntermediary",
    "796-1" => "OriginalDetailsIncomplete",
    "796-2" => "ChangeInUnderlyingOrderDetails",
    "796-99" => "Other",
    "798-1" => "CarriedCustomerSide",
    "798-2" => "CarriedNonCustomerSide",
    "798-3" => "HouseTrader",
    "798-4" => "FloorTrader",
    "798-6" => "CarriedNonCustomerSideCrossMargined",
    "798-7" => "HouseTraderCrossMargined",
    "798-8" => "JointBackOfficeAccount",
    "803-1" => "Firm",
    "803-2" => "Person",
    "803-3" => "System",
    "803-4" => "Application",
    "803-5" => "FullLegalNameOfFirm",
    "803-6" => "PostalAddress",
    "803-7" => "PhoneNumber",
    "803-8" => "EmailAddress",
    "803-9" => "ContactName",
    "803-10" => "SecuritiesAccountNumber",
    "803-11" => "RegistrationNumber",
    "803-12" => "RegisteredAddressForConfirmation",
    "803-13" => "RegulatoryStatus",
    "803-14" => "RegistrationName",
    "803-15" => "CashAccountNumber",
    "803-16" => "Bic",
    "803-17" => "CsdParticipantMemberCode",
    "803-18" => "RegisteredAddress",
    "803-19" => "FundAccountName",
    "803-20" => "TelexNumber",
    "803-21" => "FaxNumber",
    "803-22" => "SecuritiesAccountName",
    "803-23" => "CashAccountName",
    "803-24" => "Department",
    "803-25" => "LocationDesk",
    "803-26" => "PositionAccountType",
    "808-1" => "PendingAccept",
    "808-2" => "PendingRelease",
    "808-3" => "PendingReversal",
    "808-4" => "Accept",
    "808-5" => "BlockLevelReject",
    "808-6" => "AccountLevelReject",
    "814-0" => "NoActionTaken",
    "814-1" => "QueueFlushed",
    "814-2" => "OverlayLast",
    "814-3" => "EndSession",
    "815-0" => "NoActionTaken",
    "815-1" => "QueueFlushed",
    "815-2" => "OverlayLast",
    "815-3" => "EndSession",
    "819-0" => "NoAveragePricing",
    "819-1" => "Trade",
    "819-2" => "LastTrade",
    "826-0" => "AllocationNotRequired",
    "826-1" => "AllocationRequired",
    "826-2" => "UseAllocationProvidedWithTheTrade",
    "827-0" => "ExpireOnTradingSessionClose",
    "827-1" => "ExpireOnTradingSessionOpen",
    "828-0" => "RegularTrade",
    "828-1" => "BlockTrade",
    "828-2" => "Efp",
    "828-3" => "Transfer",
    "828-4" => "LateTrade",
    "828-5" => "TTrade",
    "828-6" => "WeightedAveragePriceTrade",
    "828-7" => "BunchedTrade",
    "828-8" => "LateBunchedTrade",
    "828-9" => "PriorReferencePriceTrade",
    "828-10" => "AfterHoursTrade",
    "835-0" => "Floating",
    "835-1" => "Fixed",
    "836-0" => "Price",
    "836-1" => "BasisPoints",
    "836-2" => "Ticks",
    "836-3" => "PriceTier",
    "837-0" => "OrBetter",
    "837-1" => "Strict",
    "837-2" => "OrWorse",
    "838-1" => "MoreAggressive",
    "838-2" => "MorePassive",
    "840-1" => "Local",
    "840-2" => "National",
    "840-3" => "Global",
    "840-4" => "NationalExcludingLocal",
    "841-0" => "Floating",
    "841-1" => "Fixed",
    "842-0" => "Price",
    "842-1" => "BasisPoints",
    "842-2" => "Ticks",
    "842-3" => "PriceTier",
    "843-0" => "OrBetter",
    "843-1" => "Strict",
    "843-2" => "OrWorse",
    "844-1" => "MoreAggressive",
    "844-2" => "MorePassive",
    "846-1" => "Local",
    "846-2" => "National",
    "846-3" => "Global",
    "846-4" => "NationalExcludingLocal",
    "847-1" => "Vwap",
    "847-2" => "Participate",
    "847-3" => "MininizeMarketImpact",
    "851-1" => "AddedLiquidity",
    "851-2" => "RemovedLiquidity",
    "851-3" => "LiquidityRoutedOut",
    "852-Y" => "Yes",
    "852-N" => "No",
    "853-0" => "DealerSoldShort",
    "853-1" => "DealerSoldShortExempt",
    "853-2" => "SellingCustomerSoldShort",
    "853-3" => "SellingCustomerSoldShortExempt",
    "853-4" => "QualifiedServiceRepresentative",
    "853-5" => "QsrOrAguContraSideSoldShortExempt",
    "854-0" => "Units",
    "854-1" => "Contracts",
    "856-0" => "Submit",
    "856-1" => "Alleged",
    "856-2" => "Accept",
    "856-3" => "Decline",
    "856-4" => "Addendum",
    "856-5" => "No",
    "856-6" => "TradeReportCancel",
    "856-7" => "LockedIn",
    "857-0" => "NotSpecified",
    "857-1" => "ExplicitListProvided",
    "865-1" => "Put",
    "865-2" => "Call",
    "865-3" => "Tender",
    "865-4" => "SinkingFundCall",
    "865-99" => "Other",
    "871-1" => "Flat",
    "871-2" => "ZeroCoupon",
    "871-3" => "InterestBearing",
    "871-4" => "NoPeriodicPayments",
    "871-5" => "VariableRate",
    "871-6" => "LessFeeForPut",
    "871-7" => "SteppedCoupon",
    "871-8" => "CouponPeriod",
    "871-9" => "When",
    "871-10" => "OriginalIssueDiscount",
    "871-11" => "Callable",
    "871-12" => "EscrowedToMaturity",
    "871-13" => "EscrowedToRedemptionDate",
    "871-14" => "PreRefunded",
    "871-15" => "InDefault",
    "871-16" => "Unrated",
    "871-17" => "Taxable",
    "871-18" => "Indexed",
    "871-19" => "SubjectToAlternativeMinimumTax",
    "871-20" => "OriginalIssueDiscountPrice",
    "871-21" => "CallableBelowMaturityValue",
    "871-22" => "CallableWithoutNotice",
    "871-99" => "Text",
    "875-1" => "Program3a3",
    "875-2" => "Program42",
    "875-99" => "Other",
    "891-0" => "Absolute",
    "891-1" => "PerUnit",
    "891-2" => "Percentage",
    "893-Y" => "Yes",
    "893-N" => "No",
    "895-0" => "Initial",
    "895-1" => "Scheduled",
    "895-2" => "TimeWarning",
    "895-3" => "MarginDeficiency",
    "895-4" => "MarginExcess",
    "895-5" => "ForwardCollateralDemand",
    "895-6" => "EventOfDefault",
    "895-7" => "AdverseTaxEvent",
    "896-0" => "TradeDate",
    "896-1" => "GcInstrument",
    "896-2" => "CollateralInstrument",
    "896-3" => "SubstitutionEligible",
    "896-4" => "NotAssigned",
    "896-5" => "PartiallyAssigned",
    "896-6" => "FullyAssigned",
    "896-7" => "OutstandingTrades",
    "903-0" => "New",
    "903-1" => "Replace",
    "903-2" => "Cancel",
    "903-3" => "Release",
    "903-4" => "Reverse",
    "905-0" => "Received",
    "905-1" => "Accepted",
    "905-2" => "Declined",
    "905-3" => "Rejected",
    "906-0" => "UnknownDeal",
    "906-1" => "UnknownOrInvalidInstrument",
    "906-2" => "UnauthorizedTransaction",
    "906-3" => "InsufficientCollateral",
    "906-4" => "InvalidTypeOfCollateral",
    "906-5" => "ExcessiveSubstitution",
    "906-99" => "Other",
    "910-0" => "Unassigned",
    "910-1" => "PartiallyAssigned",
    "910-2" => "AssignmentProposed",
    "910-3" => "Assigned",
    "910-4" => "Challenged",
    "919-0" => "VersusPayment",
    "919-1" => "Free",
    "919-2" => "TriParty",
    "919-3" => "HoldInCustody",
    "924-1" => "LogOnUser",
    "924-2" => "LogOffUser",
    "924-3" => "ChangePasswordForUser",
    "924-4" => "RequestIndividualUserStatus",
    "926-1" => "LoggedIn",
    "926-2" => "NotLoggedIn",
    "926-3" => "UserNotRecognised",
    "926-4" => "PasswordIncorrect",
    "926-5" => "PasswordChanged",
    "926-6" => "Other",
    "928-1" => "Connected",
    "928-2" => "NotConnectedUnexpected",
    "928-3" => "NotConnectedExpected",
    "928-4" => "InProcess",
    "935-1" => "Snapshot",
    "935-2" => "Subscribe",
    "935-4" => "StopSubscribing",
    "935-8" => "LevelOfDetail",
    "937-1" => "Full",
    "937-2" => "IncrementalUpdate",
    "939-0" => "Accepted",
    "939-1" => "Rejected",
    "940-1" => "Received",
    "940-2" => "ConfirmRejected",
    "940-3" => "Affirmed",
    "944-0" => "Retain",
    "944-1" => "Add",
    "944-2" => "Remove",
    "945-0" => "Accepted",
    "945-1" => "AcceptedWithWarnings",
    "945-2" => "Completed",
    "945-3" => "CompletedWithWarnings",
    "945-4" => "Rejected",
    "946-0" => "Successful",
    "946-1" => "InvalidOrUnknownInstrument",
    "946-2" => "InvalidOrUnknownCollateralType",
    "946-3" => "InvalidParties",
    "946-4" => "InvalidTransportTypeRequested",
    "946-5" => "InvalidDestinationRequested",
    "946-6" => "NoCollateralFoundForTheTradeSpecified",
    "946-7" => "NoCollateralFoundForTheOrderSpecified",
    "946-8" => "CollateralInquiryTypeNotSupported",
    "946-9" => "UnauthorizedForCollateralInquiry",
    "946-99" => "Other",
};
